"""Roteiros de ampliacao: nao acrescentam requisitos a avaliacao das licoes."""


def guia(revisar, modelo, etapas, testes, ampliacao):
    return {"revisar": revisar, "modelo": modelo, "etapas": etapas,
            "testes": testes, "ampliacao": ampliacao}


GUIAS_PROJETOS = {
    "calculadora": guia(
        ["scanf", "divisão", "switch", "retorno", "validação"],
        "Dois operandos double, um operador char e um resultado separado da indicação de sucesso. A função de cálculo não precisa ler o teclado.",
        ["Implemente e teste cada operação com valores conhecidos antes de acrescentar entrada pelo teclado.",
         "Leia os operandos e o operador. Confira as três conversões antes de usar qualquer resultado da leitura.",
         "Recuse operador desconhecido e divisor zero antes de calcular; defina uma resposta para resultados fora da faixa utilizável.",
         "Na submissão do exercício, respeite a ordem de entrada e o texto de saída indicados no enunciado, sem mensagens adicionais do exemplo de estudo.",
         "Para um menu repetido, leia a linha inteira e converta números com validação, evitando que uma entrada inválida fique presa no fluxo."],
        [("8 / 2", "Resultado 4.00."), ("8 / 0", "Recusa sem executar a divisão."),
         ("3 - 8", "Resultado -5.00, mantendo o sinal."),
         ("Operador ? ou texto no lugar de número", "Erro tratado sem usar valores não lidos.")],
        "Depois do exercício, acrescente repetição, opção de saída e histórico. Defina a política para caracteres restantes na linha; scanf confirmar campos não garante que a linha inteira era válida."),
    "cadastro": guia(
        ["structs", "arrays", "fgets", "strcpy", "validação"],
        "Pessoa com nome e idade; array de registros; quantidade usada separada da capacidade. Na versão ampliada, cada pessoa recebe um identificador estável.",
        ["Comece pelo recorte avaliado: uma pessoa, nome sem espaços e idade, produzindo a frase solicitada.",
         "Para vários registros, faça uma função de inclusão que receba a coleção e sua quantidade.",
         "Monte um registro temporário e valide os campos antes de confirmar a inclusão.",
         "Liste somente as posições preenchidas; trate cadastro vazio e capacidade atingida.",
         "Ao permitir nomes completos, use leitura por linha e defina o tratamento de linhas longas. Ao persistir, mantenha um formato documentado."],
        [("Um nome e uma idade válidos", "Um registro completo e quantidade aumentada uma vez."),
         ("Nome maior que o campo ou idade fora da faixa", "Inclusão recusada, quantidade anterior preservada."),
         ("Tentativa além da capacidade", "Nenhuma escrita fora do array."),
         ("Listagem vazia", "Nenhum acesso a registro não inicializado.")],
        "Adicione busca por identificador, edição e remoção. Depois implemente salvar e carregar, verificando registros incompletos e erros de arquivo."),
    "agenda": guia(
        ["structs", "arrays", "strcmp", "busca linear", "fgets"],
        "Contato com nome e telefone em arrays de char. Uma coleção contém os registros válidos; uma busca retorna posição ou -1.",
        ["Crie dois contatos conhecidos e mantenha telefone como texto, preservando zeros e símbolos.",
         "Implemente a busca exata com strcmp e percorra apenas a quantidade cadastrada.",
         "Confira o resultado da busca antes de acessar a coleção. Exiba uma resposta definida para ausência.",
         "No exercício, use o nome e o telefone pedidos no enunciado; os dados do exemplo explicado são diferentes para você aplicar a ideia.",
         "Ao ampliar, defina se nomes repetidos são permitidos e use identificadores para operações de edição e remoção."],
        [("Buscar primeiro e último contato", "Telefone associado ao contato correto."),
         ("Buscar nome inexistente", "Retorno de ausência, sem acesso ao índice -1."),
         ("Telefone começando por 0", "Zero inicial preservado."),
         ("Nome com diferença de maiúsculas", "Comportamento coerente com a política de busca escolhida.")],
        "Inclua novos contatos, remova mantendo a associação entre campos e salve em arquivo. Busca parcial e ordenação podem vir depois da busca exata."),
    "jogo terminal": guia(
        ["scanf", "if", "while", "break", "continue"],
        "Número secreto, tentativa atual e condição de encerramento. A ampliação pode incluir contador e limite de tentativas.",
        ["Use um segredo fixo durante os testes. No exercício avaliado, o alvo deve ser o valor solicitado, não o valor do exemplo explicado.",
         "Leia uma tentativa por passagem do laço e trate falha ou encerramento da entrada.",
         "Compare somente uma tentativa válida com o segredo; acerto precisa interromper a repetição.",
         "Na versão ampliada, informe se o segredo é maior ou menor e decida se entradas inválidas contam como tentativa.",
         "Adicione sorteio apenas após validar o ciclo. Inicialize a semente uma vez, não a cada palpite."],
        [("Acerto na primeira tentativa", "Encerra sem solicitar outro palpite."),
         ("Tentativa menor, maior e igual", "Respostas consistentes e encerramento no acerto."),
         ("Texto inválido ou fim da entrada", "Sem laço infinito nem reutilização de valor antigo."),
         ("Valor fora do intervalo da versão ampliada", "Tratamento conforme a regra definida.")],
        "Acrescente limite de tentativas, nova partida e dificuldade. Mantenha uma forma de testar com segredo conhecido, independentemente do sorteio."),
    "sistema biblioteca": guia(
        ["structs", "enum", "ponteiros + funções", "busca linear", "fprintf"],
        "Livro com identificador, título e estado. O empréstimo é uma mudança de estado validada, não apenas uma mensagem na tela.",
        ["Defina os estados disponível e emprestado, usando os campos exigidos no exercício para a submissão.",
         "Implemente emprestar recebendo um ponteiro para o livro; recuse a operação quando ele já estiver emprestado.",
         "Confirme a alteração apenas no sucesso e teste a mesma operação duas vezes.",
         "Na ampliação, busque o livro por identificador antes de emprestar ou devolver. Não encontrado não pode alterar outro livro.",
         "Persista os dados após operações válidas e confira escrita e fechamento antes de confirmar salvamento."],
        [("Emprestar livro disponível", "Estado alterado uma vez e sucesso informado."),
         ("Emprestar o mesmo livro novamente", "Recusa sem nova alteração."),
         ("Devolver livro emprestado na ampliação", "Volta a ficar disponível."),
         ("Identificador inexistente ou erro ao salvar", "Falha explícita, sem confirmação falsa de sucesso.")],
        "Adicione leitores, vínculo de quem retirou, fila de reservas e arquivo de registros. Comece por uma coleção pequena antes de trocar a estrutura de armazenamento."),
    "editor texto": guia(
        ["strings", "strlen", "strcat", "fgets", "buffer overflow"],
        "Buffer de capacidade fixa contendo uma string válida. Toda modificação mantém o terminador e respeita a capacidade total.",
        ["Inicialize o texto, inclusive quando estiver vazio, e conheça a capacidade disponível.",
         "Antes de acrescentar, confira comprimento atual mais acréscimo mais terminador.",
         "Execute a concatenação somente se couber inteira. Caso contrário, preserve o conteúdo anterior.",
         "Teste os limites exatos: caber com o terminador e exceder por um byte são casos diferentes.",
         "Ao ampliar para leitura e salvamento, trate linhas grandes, falha de abertura, escrita e fechamento."],
        [("Texto inicial e acréscimo do exercício", "Resultado textual exatamente solicitado."),
         ("Conteúdo ocupando capacidade menos um byte", "Terminador ainda dentro do buffer."),
         ("Acréscimo um byte maior do que cabe", "Recusa sem mudar o texto anterior."),
         ("Texto vazio e acréscimo vazio", "String válida, sem acesso indevido.")],
        "Acrescente limpar, salvar e carregar. Inserção no meio exige mover regiões com cuidado; desfazer pode ser estudado depois com uma pilha de ações."),
    "projeto final": guia(
        ["parâmetros", "retorno", "arrays", "validação", ".h", "makefile"],
        "Para o resumo de notas: coleção de notas, quantidade e resultado calculado por função. Para a entrega ampliada: dados, operações e persistência com responsabilidades separadas.",
        ["Escreva entradas aceitas, faixa das notas, operações e resultados esperados. Na submissão, siga os requisitos específicos do enunciado.",
         "Implemente o cálculo em função e confira-o com dados conhecidos. Quantidade zero não pode chegar à divisão.",
         "Adicione leitura validada; só encaminhe valores aceitos para o cálculo.",
         "Na ampliação, organize funções em arquivos próprios e documente como construir o programa. Preserve a possibilidade de testar cálculos sem o menu.",
         "Acrescente persistência e teste reabertura. Prepare uma demonstração com caso normal, limite e falha tratada, registrando os resultados."],
        [("Notas 7, 8 e 9", "Média 8.00 na saída exigida."),
         ("Nota fora da faixa ou texto inválido", "Entrada recusada antes do cálculo."),
         ("Coleção vazia na função ampliada", "Falha informada sem dividir por zero."),
         ("Salvar, encerrar e reabrir na ampliação", "Registros recuperados sem perda; arquivo inválido é tratado.")],
        "A entrega completa pode incluir menu, vários alunos, busca, ordenação e arquivo. Apresente requisitos atendidos, limitações conhecidas e testes, sem confundir o recorte avaliado com todo o sistema."),
}
