"""Consulta rápida de C: formatos, tipos, operadores, funções, erros do GCC e glossário."""

FORMATOS = (
    ("%d ou %i", "int", 'printf("%d", idade);  scanf("%d", &idade);'),
    ("%u", "unsigned int", 'printf("%u", quantidade);'),
    ("%ld", "long", 'printf("%ld", populacao);'),
    ("%lld", "long long", 'printf("%lld", grande);'),
    ("%f", "float ou double no printf; float no scanf", 'printf("%f", media);  scanf("%f", &nota);'),
    ("%lf", "double no scanf", 'scanf("%lf", &valor);'),
    ("%.2f", "decimal com 2 casas", 'printf("%.2f", preco);  // 12.50'),
    ("%e", "notação científica", 'printf("%e", 1500.0);  // 1.500000e+03'),
    ("%c", "char", 'scanf(" %c", &letra);  // o espaço ignora o Enter anterior'),
    ("%s", "string (texto)", 'scanf("%29s", nome);  // sem &, com limite'),
    ("%p", "endereço de memória", 'printf("%p", (void *) &idade);'),
    ("%x ou %X", "inteiro em hexadecimal", 'printf("%x", 255);  // ff'),
    ("%zu", "size_t (sizeof, strlen)", 'printf("%zu", strlen(nome));'),
    ("%%", "o próprio símbolo %", 'printf("100%%");'),
    ("%5d e %-10s", "largura mínima; o - alinha à esquerda", 'printf("[%5d]", 42);  // [   42]'),
)

TIPOS = (
    ("char", "1 byte", "-128 a 127 (unsigned char: 0 a 255)"),
    ("short", "2 bytes", "-32.768 a 32.767"),
    ("int", "4 bytes", "-2.147.483.648 a 2.147.483.647"),
    ("unsigned int", "4 bytes", "0 a 4.294.967.295"),
    ("long", "8 bytes no Linux 64 bits (4 no Windows)", "igual a long long no Linux 64 bits"),
    ("long long", "8 bytes", "cerca de -9,2 × 10¹⁸ a 9,2 × 10¹⁸"),
    ("float", "4 bytes", "cerca de 6 a 7 dígitos de precisão"),
    ("double", "8 bytes", "cerca de 15 a 16 dígitos de precisão"),
    ("bool (stdbool.h)", "1 byte", "true (1) ou false (0)"),
    ("ponteiro (tipo *)", "8 bytes em sistemas 64 bits", "guarda um endereço de memória"),
)

OPERADORES = (
    ("() [] -> .  x++ x--", "chamada, índice, membro, pós-incremento", "esquerda → direita"),
    ("++x --x  +x -x  !  ~  (tipo)  *p  &x  sizeof", "unários", "direita → esquerda"),
    ("*  /  %", "multiplicação, divisão, resto", "esquerda → direita"),
    ("+  -", "soma e subtração", "esquerda → direita"),
    ("<<  >>", "deslocamento de bits", "esquerda → direita"),
    ("<  <=  >  >=", "comparação", "esquerda → direita"),
    ("==  !=", "igualdade", "esquerda → direita"),
    ("&", "E bit a bit", "esquerda → direita"),
    ("^", "OU exclusivo bit a bit", "esquerda → direita"),
    ("|", "OU bit a bit", "esquerda → direita"),
    ("&&", "E lógico", "esquerda → direita"),
    ("||", "OU lógico", "esquerda → direita"),
    ("?:", "ternário", "direita → esquerda"),
    ("=  +=  -=  *=  /=  %=  &=  ^=  |=  <<=  >>=", "atribuição", "direita → esquerda"),
    (",", "vírgula", "esquerda → direita"),
)

ESCAPES = (
    ("\\n", "nova linha"),
    ("\\t", "tabulação"),
    ("\\\\", "barra invertida"),
    ('\\"', "aspas duplas dentro de um texto"),
    ("\\'", "apóstrofo dentro de um caractere"),
    ("\\0", "caractere nulo: marca o fim de uma string"),
    ("\\r", "volta ao início da linha"),
)

FUNCOES = (
    ("stdio.h", (
        ("printf(formato, ...)", "Mostra texto formatado na tela."),
        ("scanf(formato, &var)", "Lê do teclado; retorna quantos valores conseguiu ler."),
        ("fgets(texto, tamanho, stdin)", "Lê uma linha inteira com limite de tamanho (guarda o Enter)."),
        ("puts(texto)", "Mostra o texto e pula linha."),
        ("putchar(c) / getchar()", "Escreve / lê um único caractere."),
        ("fopen(caminho, modo)", 'Abre arquivo ("r" ler, "w" gravar, "a" acrescentar); retorna NULL se falhar.'),
        ("fclose(arquivo)", "Fecha o arquivo e grava o que estava pendente."),
        ("fprintf / fscanf", "Iguais a printf / scanf, mas em um arquivo."),
    )),
    ("string.h", (
        ("strlen(texto)", "Quantidade de caracteres, sem contar o \\0."),
        ("strcpy(destino, origem)", "Copia o texto; o destino precisa ter espaço suficiente."),
        ("strncpy(destino, origem, n)", "Copia no máximo n caracteres."),
        ("strcmp(a, b)", "Compara textos: 0 se iguais, negativo ou positivo conforme a ordem."),
        ("strcat(destino, origem)", "Junta origem no fim de destino."),
        ("strchr(texto, c) / strstr(texto, trecho)", "Procura um caractere / um trecho; retorna NULL se não achar."),
        ('strcspn(texto, "\\n")', "Posição do primeiro Enter; usado para remover o Enter do fgets."),
    )),
    ("stdlib.h", (
        ("malloc(bytes)", "Reserva memória sem limpar; retorna NULL se faltar memória."),
        ("calloc(quantidade, tamanho)", "Reserva memória já zerada."),
        ("realloc(ponteiro, novo_tamanho)", "Aumenta ou diminui um bloco reservado."),
        ("free(ponteiro)", "Libera memória reservada com malloc, calloc ou realloc."),
        ("strtol(texto, &fim, 10)", "Converte texto em número e permite detectar erros."),
        ("atoi(texto)", "Converte texto em int, mas não avisa quando o texto é inválido."),
        ("rand() / srand(semente)", "Número pseudoaleatório / define a semente (ex.: srand(time(NULL)))."),
        ("abs(n)", "Valor absoluto de um int."),
        ("exit(EXIT_SUCCESS)", "Encerra o programa informando sucesso (EXIT_FAILURE para erro)."),
    )),
    ("math.h (o compilador usa -lm)", (
        ("sqrt(x)", "Raiz quadrada."),
        ("pow(base, expoente)", "Potência."),
        ("fabs(x)", "Valor absoluto de um double."),
        ("ceil(x) / floor(x) / round(x)", "Arredonda para cima / para baixo / para o mais próximo."),
        ("sin(x) / cos(x)", "Seno e cosseno; o ângulo é em radianos."),
    )),
    ("ctype.h", (
        ("isdigit(c) / isalpha(c) / isspace(c)", "Testa se é dígito / letra / espaço."),
        ("toupper(c) / tolower(c)", "Converte para maiúscula / minúscula."),
    )),
)

ERROS_GCC = (
    ("expected ';' before ... (ou expected ',' or ';' before ...)", "Faltou ponto e vírgula no fim da instrução anterior.",
     "Coloque ; no fim da linha indicada ou da linha de cima."),
    ("'x' undeclared (first use in this function)", "A variável não foi declarada ou o nome está escrito diferente.",
     "Declare a variável antes de usar e confira maiúsculas e minúsculas."),
    ("implicit declaration of function 'printf'", "A função foi usada sem o cabeçalho ou protótipo.",
     "Inclua o cabeçalho certo (ex.: #include <stdio.h>) ou declare o protótipo antes do main."),
    ("format '%d' expects argument of type 'int', but argument 2 has type 'double'",
     "O especificador do printf não combina com o tipo da variável.", "Use %f para double e %d para int."),
    ("format '%d' expects argument of type 'int *', but argument 2 has type 'int'",
     "Faltou o & no scanf.", 'Escreva scanf("%d", &numero);'),
    ("control reaches end of non-void function", "Algum caminho da função termina sem return.",
     "Garanta um return com valor em todos os caminhos."),
    ("suggest parentheses around assignment used as truth value",
     "Foi usado = (atribuição) onde provavelmente era == (comparação).", "Troque if (x = 5) por if (x == 5)."),
    ("'x' is used uninitialized", "A variável foi lida antes de receber um valor.",
     "Inicialize na declaração, por exemplo int soma = 0;"),
    ("unused variable 'x'", "Aviso: a variável foi declarada e nunca usada.", "Use a variável ou remova a declaração."),
    ("expected declaration or statement at end of input", "Alguma chave { ficou sem o } correspondente.",
     "Confira se cada { tem o seu }."),
    ("comparison between pointer and integer", "Um ponteiro ou texto foi comparado com um número ou caractere.",
     "Para comparar uma letra use texto[0] == 'a'; para textos, strcmp."),
    ("undefined reference to 'funcao'", "Erro de ligação: a função foi declarada mas não foi escrita (definida).",
     "Escreva o corpo da função ou confira o nome."),
    ("Process returned -11 (falha de segmentação)", "O programa acessou memória inválida.",
     "Confira ponteiros NULL, índices fora do vetor e scanf sem &."),
    ("Process returned -8 (erro aritmético)", "Houve divisão inteira por zero.", "Teste se o divisor é zero antes de dividir."),
)

GLOSSARIO = (
    ("Algoritmo", "Sequência de passos para resolver um problema."),
    ("Código-fonte", "O texto do programa, escrito em C, em arquivos .c e .h."),
    ("Compilador", "Programa (como o GCC) que traduz o código-fonte para linguagem de máquina."),
    ("Pré-processador", "Etapa antes da compilação que trata as linhas com # (#include, #define)."),
    ("Ligador (linker)", "Junta o código compilado com as bibliotecas e gera o executável."),
    ("Executável", "O programa pronto para rodar, resultado da compilação e da ligação."),
    ("Variável", "Espaço na memória, com nome e tipo, que guarda um valor."),
    ("Tipo", "Define que valores uma variável guarda e quanto espaço ocupa (int, double, char...)."),
    ("Constante", "Valor que não muda durante o programa (const ou #define)."),
    ("Função", "Bloco de código com nome, que pode receber parâmetros e retornar um valor."),
    ("Protótipo", "Declaração da função (nome, retorno e parâmetros) antes de ela ser usada."),
    ("Escopo", "Parte do programa em que um nome (variável, função) pode ser usado."),
    ("Laço (loop)", "Estrutura que repete instruções: while, do while e for."),
    ("Recursão", "Quando uma função chama a si mesma até chegar a um caso de parada."),
    ("Vetor (array)", "Sequência de valores do mesmo tipo, acessados por índice a partir de 0."),
    ("String", "Texto em C: um vetor de char terminado pelo caractere nulo \\0."),
    ("Ponteiro", "Variável que guarda o endereço de outra variável."),
    ("Endereço", "Posição de um dado na memória; obtido com o operador &."),
    ("Desreferenciar", "Acessar o valor apontado por um ponteiro, usando *."),
    ("Struct", "Tipo criado pelo programador que agrupa vários campos."),
    ("Alocação dinâmica", "Reservar memória durante a execução com malloc, calloc ou realloc."),
    ("Heap", "Região da memória usada pela alocação dinâmica."),
    ("Pilha de chamadas (stack)", "Região da memória com as variáveis locais das funções em execução."),
    ("Vazamento de memória", "Memória reservada que nunca é liberada com free."),
    ("Buffer overflow", "Escrever além do tamanho de um vetor, corrompendo outros dados."),
    ("Comportamento indefinido", "Situação em que o padrão C não garante o resultado, como ler fora de um vetor."),
    ("Cabeçalho (.h)", "Arquivo com declarações compartilhadas, incluído com #include."),
    ("Biblioteca padrão", "Conjunto de funções que acompanha o C: stdio, stdlib, string, math..."),
)
