"""Leituras complementares; nao altera respostas, IDs ou regras dos exercicios."""


def aprofundar(objetivo, explicacao, passos, aplicacao, pergunta, resposta):
    return {
        "objetivo": objetivo,
        "explicacao": explicacao,
        "passos": passos,
        "aplicacao": aplicacao,
        "pergunta": pergunta,
        "resposta": resposta,
    }


LEITURAS = {
    "O que é C": aprofundar(
        "Distinguir o texto de um programa do programa em execução.",
        "Programar é descrever uma sequência de ações com regras precisas. O arquivo .c contém instruções legíveis; o compilador verifica essas instruções e produz um programa para um ambiente específico. O mesmo texto pode ser adaptado para vários sistemas, mas um executável de Windows não é automaticamente um executável de Linux. Desempenho também depende do algoritmo escolhido: usar C, sozinho, não torna qualquer solução rápida.",
        ["Observe main como o começo da execução. Não é necessário decorar todos os símbolos nesta primeira leitura.", "O texto entre aspas é a mensagem exibida. O programa termina depois das instruções de main."],
        "Na calculadora e na agenda, o ponto de partida será sempre identificar quais dados entram, quais ações acontecem e o que deve aparecer como resultado.",
        "Mudar o texto do arquivo .c altera um executável que já foi criado?",
        "Não. É preciso construir novamente o programa para que o executável contenha a mudança."),
    "Estrutura básica": aprofundar(
        "Reconhecer o papel de cada parte de um programa pequeno.",
        "#include apresenta ao compilador as declarações de uma biblioteca; ele não é uma ordem para mostrar algo na tela. Em int main(void), int indica um resultado inteiro e void informa que não há parâmetros. As chaves agrupam instruções. return 0 comunica encerramento com sucesso ao ambiente; esse zero não é uma mensagem impressa. Em programas comuns do curso, main é o ponto inicial; sistemas embarcados podem adotar outra forma de inicialização.",
        ["Leia de fora para dentro: biblioteca, função principal e instruções dentro das chaves.", "A variável resposta recebe 42, printf exibe esse valor e return encerra a função. Variáveis serão estudadas em detalhe no módulo 3."],
        "Essa organização permanece nos projetos maiores; novas funções ajudam a evitar que main concentre todas as tarefas.",
        'return 0 e printf("0") fazem a mesma coisa?',
        "Não. printf mostra texto; return entrega um resultado a quem chamou a função e encerra essa chamada."),
    "Comentários": aprofundar(
        "Escrever anotações que expliquem decisões sem afetar a execução.",
        "// vale até o fim da linha; /* e */ delimitam um trecho que pode ocupar várias linhas. Comentários de bloco não podem ser aninhados. Escrever esses símbolos dentro de uma string apenas os torna parte do texto. Um comentário de bloco sem fechamento deve gerar um diagnóstico do compilador: não é uma maneira válida de desligar o restante do programa.",
        ["As duas anotações do exemplo não são enviadas ao terminal.", "Somente printf produz saída. Um comentário útil diria por que existe um limite ou uma regra, em vez de repetir o nome de uma variável."],
        "No sistema de biblioteca, explique a regra que impede emprestar um livro já emprestado. A anotação deve acompanhar a regra quando ela mudar.",
        "É possível colocar um comentário /* ... */ inteiro dentro de outro?",
        "Não. O primeiro fechamento */ encerra o comentário de bloco; use comentários de linha para evitar essa confusão."),
    "Compilação": aprofundar(
        "Separar erro ao construir, erro ao executar e resultado incorreto.",
        "Antes da execução, inclusões e macros são processadas, o código é traduzido e as partes necessárias são ligadas. Uma mensagem de erro impede concluir uma construção válida. Um aviso pode permitir gerar o programa, mas merece investigação. Já uma conta errada pode compilar sem qualquer aviso: construir com sucesso não prova que o problema foi resolvido. Se houver erro, confira a primeira mensagem e também a linha anterior à indicada.",
        ["A multiplicação do exemplo é uma operação do programa; a ferramenta de compilação prepara o executável.", "Ao executar a versão construída, o resultado é 42. Depois de editar o arquivo, reconstrua antes de comparar a nova saída."],
        "Em todos os projetos, trabalhe em pequenas mudanças: construir, executar e comparar com um resultado calculado previamente.",
        "Um programa que compila pode calcular uma média errada?",
        "Sim. O compilador verifica regras da linguagem, não sabe qual fórmula o problema pretendia usar."),
    "printf": aprofundar(
        "Controlar exatamente o texto e os valores exibidos.",
        "printf usa o primeiro argumento como formato. Texto comum é copiado para a saída; \\n solicita uma nova linha e %% imprime um sinal de porcentagem. Nas lições seguintes, %d receberá int, %c receberá um caractere, %s receberá uma string e %f receberá um valor decimal promovido a double. %.2f muda a apresentação para duas casas, não a precisão guardada. Ao mostrar um texto fornecido pelo usuário, use printf(\"%s\", texto), nunca trate esse texto como formato.",
        ["O primeiro printf exibe Ola, estudante! e muda de linha.", "O segundo mostra Estou aprendendo C. A ordem das chamadas determina a ordem das mensagens."],
        "Relatórios de notas e menus de projetos precisam de rótulos claros. No exercício avaliado, respeite a mensagem pedida em seu enunciado.",
        "Como mostrar o texto 100% concluído sem interpretar % como formato?",
        "Use %% dentro do formato: printf(\"100%% concluido\\n\")."),
    "scanf": aprofundar(
        "Ler um valor no momento da execução e conferir se a leitura funcionou.",
        "Quando scanf encontra uma leitura pendente, o programa aguarda dados. Em scanf(\"%d\", &numero), %d pede um inteiro e &numero informa onde gravá-lo. O retorno é a quantidade de valores atribuídos; para um inteiro, espere 1. O exemplo usa if apenas para impedir o uso de uma leitura que falhou; decisões serão aprofundadas no módulo 5. %c não ignora espaços como %d: um espaço antes de %c no formato costuma ser necessário. Evite terminar o formato com \\n, que pode esperar mais entrada. Para textos completos e números fora da faixa, a validação com fgets e strtol será estudada adiante.",
        ["printf apresenta o pedido; fflush(stdout) solicita o envio da saída pendente antes da espera por entrada.", "Depois de digitar 12, scanf armazena o valor e o último printf mostra Numero: 12. Se digitar abc, o exemplo encerra com uma mensagem de entrada inválida."],
        "A calculadora lê dois números e um operador; o cadastro lê campos de uma pessoa. Em ambos, confira a leitura antes de alterar dados.",
        "Por que não mostrar numero depois de uma leitura que retornou 0?",
        "Nenhum inteiro foi atribuído. A variável pode continuar sem um valor válido para o cálculo."),
    "int": aprofundar(
        "Escolher um inteiro para contagens e inicializá-lo antes do uso.",
        "Uma declaração informa o tipo e o nome; uma inicialização já fornece o primeiro valor. int idade; não inicializa automaticamente uma variável local comum. C garante uma faixa mínima para int, mas não que ele ocupe quatro bytes em todo computador. INT_MIN e INT_MAX, de limits.h, indicam os limites do ambiente. Ultrapassar a faixa de um inteiro com sinal é comportamento indefinido, não uma volta garantida para o início da faixa.",
        ["int idade = 18 reserva o objeto e define seu valor inicial.", "printf usa %d porque idade é int. Mudar o nome da variável exige ajustar os lugares que fazem referência a ela."],
        "Quantidade de contatos, tentativas e livros disponíveis são contagens inteiras. Um identificador com zeros à esquerda pode precisar ser texto, não um número.",
        "Qual é a diferença entre int idade; e int idade = 0;?",
        "Na segunda forma, idade já recebe zero. Na primeira, uma variável local comum ainda não deve ser lida."),
    "float e double": aprofundar(
        "Usar decimais sem confundir armazenamento, leitura e formatação.",
        "Números decimais geralmente são aproximados em base binária; por isso 0.1 não precisa ser armazenado de forma exata. double costuma preservar mais dígitos que float, embora os detalhes dependam do ambiente. Em printf, float é promovido a double e ambos usam %f. Em scanf, o destino importa: %f exige float * e %lf exige double *. Imprimir com uma casa decimal arredonda a apresentação. Em valores monetários, considere centavos inteiros e uma regra explícita de arredondamento.",
        ["A variável nota guarda 8.5 como double.", "%.1f exibe Nota: 8.5. Trocar para %.2f exibiria 8.50, sem mudar o valor da variável."],
        "Na calculadora e no resumo de notas, decida quantas casas mostrar e quais valores de entrada são permitidos.",
        "Guardar 7 / 2 em um double produz automaticamente 3.5?",
        "Não. A divisão acontece primeiro entre inteiros e resulta em 3; use 7.0 / 2.0 para obter 3.5."),
    "char": aprofundar(
        "Distinguir um caractere, uma palavra e a representação numérica.",
        "char ocupa uma unidade de armazenamento chamada byte em C. Essa unidade possui pelo menos oito bits, mas o padrão não exige exatamente oito em toda plataforma. 'C' representa um caractere; \"C\" é uma string que inclui um terminador. ASCII é comum, não obrigatório. Em UTF-8, letras acentuadas podem usar vários bytes; um char sozinho não representa qualquer caractere que aparece na tela.",
        ["char inicial = 'C' guarda um caractere.", "%c mostra a letra. %d mostraria um valor numérico após a promoção para int, não uma palavra."],
        "Um operador da calculadora pode ser char. Nomes de pessoas, títulos e telefones devem ser tratados como strings.",
        "Um char é suficiente para guardar o nome Ana?",
        "Não. O nome precisa de um conjunto de caracteres e do terminador da string, assunto do módulo de arrays e strings."),
    "constantes": aprofundar(
        "Dar nome aos valores fixos e impedir alterações acidentais.",
        "const mantém um objeto tipado que não deve ser modificado. Inicialize-o quando for declarado. Um nome como LIMITE_CONTATOS explica a regra melhor que repetir 100 em vários pontos. Em C, const não significa que o valor possa ser usado em qualquer lugar que exija uma constante inteira de compilação, como um case. Esse uso pode exigir enum ou macro, conforme o contexto.",
        ["LIMITE recebe 100 na declaração.", "O exemplo apenas lê a constante para mostrar Limite: 100. Uma atribuição posterior a LIMITE seria inválida."],
        "A capacidade inicial de uma agenda e os limites de uma nota devem estar visíveis e ter um único significado no projeto.",
        "Por que nomear um limite que aparece em várias funções?",
        "Para que a regra fique compreensível e possa ser revisada sem procurar números soltos pelo código."),
    "#define": aprofundar(
        "Entender a substituição de macros e seus limites.",
        "#define é processado antes da compilação das funções. Na macro simples do exemplo, CURSO é substituído pelo texto \"C\". Não acrescente ponto e vírgula ao valor da macro. Macros com parâmetros precisam de parênteses nos argumentos e na expressão inteira. Mesmo com parênteses, QUADRADO(i++) pode avaliar i++ duas vezes; quando estudar funções, prefira uma função para cálculos que precisam avaliar cada argumento uma vez.",
        ["A definição fica antes de main e não reserva uma variável chamada CURSO.", "O formato %s recebe o texto substituído e o resultado é Curso: C."],
        "Macros podem nomear capacidades e opções de um projeto. Para regras mais complexas, as funções oferecem uma interface mais clara.",
        "Por que #define LIMITE 10; pode gerar problemas?",
        "O ponto e vírgula também entra na substituição e pode interromper uma expressão no lugar errado."),
    "escopo": aprofundar(
        "Reconhecer onde um nome pode ser usado sem confundir isso com sua duração.",
        "Escopo é a região do código em que um nome é visível. Duração é o período em que o objeto existe. A variável local comum costuma existir durante a execução do bloco, mas uma variável local static tem duração de todo o programa; seu nome continua restrito ao bloco. Evite declarar outro objeto com o mesmo nome dentro de um bloco menor: esse nome esconde o externo e dificulta acompanhar o valor usado.",
        ["fora é visível em main, inclusive dentro das chaves menores.", "dentro só é visível nas chaves em que foi declarado. Depois delas, o exemplo ainda pode mostrar fora, mas não acessar dentro pelo nome."],
        "No cadastro, uma variável temporária de leitura pode ser local à função. O conjunto de registros deve ser passado explicitamente às funções que o utilizam.",
        "Uma variável local static se torna global?",
        "Não. Ela permanece com nome visível apenas no seu escopo, embora seu objeto sobreviva entre chamadas."),
    "soma": aprofundar(
        "Acompanhar os operandos e o tipo usado para calcular um total.",
        "O resultado de a + b é calculado antes de ser atribuído a outra variável. Por isso, guardar o resultado em um tipo maior não corrige um estouro que já aconteceu na expressão. + soma números; não junta strings em C. Ao acumular vários valores, defina um total inicial, normalmente zero, e adicione uma parcela por vez. Parênteses ajudam a deixar a intenção explícita em contas maiores.",
        ["a recebe 19 e b recebe 23.", "a + b produz 42, que é passado para printf. As duas variáveis originais permanecem com os mesmos valores."],
        "A soma aparece no total de itens, nas notas e no saldo de um cadastro de produtos.",
        "Executar total + valor; muda total?",
        "Não. Para armazenar a soma, escreva total = total + valor; ou total += valor; quando essa forma for estudada."),
    "subtração": aprofundar(
        "Representar diferenças e verificar se um saldo pode ficar negativo.",
        "A ordem dos operandos muda o resultado: saldo - retirada representa o que resta, enquanto retirada - saldo representa outra diferença. Unsigned não representa valores negativos; sua aritmética usa uma faixa circular. Isso não é uma boa forma de sinalizar que faltou saldo. Quando a regra proibir valores negativos, valide a retirada antes de atualizar o estado, usando decisões nas próximas lições.",
        ["O exemplo começa com saldo 100 e retirada 58.", "A diferença é 42. A expressão mostrada não altera a variável saldo, a menos que o resultado seja atribuído a ela."],
        "Num sistema de biblioteca, devolver um livro ou descontar uma quantidade exige conferir a regra antes de diminuir um contador.",
        "Uma quantidade unsigned que passa abaixo de zero vira um número negativo?",
        "Não. Ela dá a volta dentro da faixa do tipo; verifique os limites antes da operação."),
    "multiplicação": aprofundar(
        "Modelar produtos e considerar a faixa do resultado.",
        "Multiplicação tem prioridade sobre soma e subtração: 2 + 3 * 4 é 14, enquanto (2 + 3) * 4 é 20. Escolha parênteses para representar a fórmula pretendida. Em contas com valores grandes, os operandos precisam ter um tipo suficiente antes de multiplicar. O símbolo * também será usado em ponteiros; é a posição na declaração ou expressão que determina o significado.",
        ["linhas vale 6 e colunas vale 7.", "O produto representa 42 células. A operação é feita com inteiros, e %d mostra seu resultado."],
        "Matrizes e buffers usam tamanho por quantidade. Ao alocar memória mais adiante, confira também se esse produto cabe no tipo usado para tamanhos.",
        "Qual conta representa três caixas com quatro itens, mais dois itens soltos?",
        "3 * 4 + 2, cujo resultado é 14. Os parênteses podem reforçar a leitura: (3 * 4) + 2."),
    "divisão": aprofundar(
        "Escolher entre divisão inteira e decimal.",
        "Em C11, a divisão de inteiros descarta a fração em direção a zero: -7 / 2 é -3. Se pelo menos um operando tiver tipo decimal adequado, a operação preserva uma aproximação da fração. O operador % calcula resto apenas para inteiros. Nunca divida por zero. Para inteiros com sinal, existe ainda o caso extremo INT_MIN / -1, cujo resultado pode não caber no tipo. Não confunda formatar com duas casas com mudar o cálculo realizado.",
        ["7.0 e 2.0 fazem a operação acontecer como double.", "O resultado 3.5 é exibido como Resultado: 3.50 por causa de %.2f."],
        "Na calculadora, valide o divisor. Para calcular médias, use uma quantidade decimal ou uma conversão antes de dividir.",
        "Por que (double)(7 / 2) não resolve a perda da fração?",
        "Porque 7 / 2 já resultou em 3. Converta antes: (double)7 / 2."),
    "operadores relacionais": aprofundar(
        "Escrever comparações que representem exatamente uma regra.",
        "<, <=, >, >=, == e != produzem int com valor 0 ou 1. Em uma condição, qualquer valor diferente de zero é tratado como verdadeiro, mas o resultado desses operadores é especificamente 0 ou 1. = atribui e == compara. Para testar uma faixa, não escreva 0 <= nota <= 10: C avalia a primeira comparação e depois compara seu 0 ou 1 com 10. Use duas comparações ligadas por &&.",
        ["a é 42 e b é 20; portanto a > b produz 1.", "a == b produz 0. Observe os rótulos para relacionar cada número à comparação correta."],
        "Validar idade, capacidade de uma lista e disponibilidade exige condições com limites bem definidos.",
        "Qual é a forma correta de testar se nota está entre 0 e 10?",
        "nota >= 0 && nota <= 10. São duas comparações ligadas pelo operador lógico E."),
    "operadores lógicos": aprofundar(
        "Combinar condições e usar o curto-circuito com intenção.",
        "&& representa E, || representa OU e ! nega uma condição. Em A && B, B só é avaliada se A for verdadeira; em A || B, B só é avaliada se A for falsa. Assim, uma verificação pode proteger uma operação que vem depois. && e || devolvem 0 ou 1, não um dos valores originais. Use parênteses em combinações maiores e evite esconder alterações de variáveis dentro das condições.",
        ["10 > 5 e 3 < 8 são verdadeiras.", "A combinação com && produz 1, guardado em resultado e mostrado no terminal."],
        "Um empréstimo pode exigir livro disponível E usuário autorizado. Uma entrada deve ser rejeitada quando falha no formato OU está fora da faixa.",
        "Em divisor != 0 && total / divisor > 2, a divisão ocorre se divisor for zero?",
        "Não. A primeira condição é falsa, então o curto-circuito impede avaliar a segunda."),
    "incremento": aprofundar(
        "Atualizar contadores sem depender de uma ordem ambígua.",
        "Em um comando isolado, contador++ e ++contador aumentam o valor em uma unidade. Dentro de uma expressão, a forma pós-fixa fornece o valor anterior e a pré-fixa fornece o valor atualizado. Isso não permite supor a ordem de avaliação de vários argumentos de uma função. Evite exemplos como printf(\"%d %d\", i++, i++): modificar o mesmo objeto sem o sequenciamento necessário pode ter comportamento indefinido.",
        ["contador começa em 40 e contador++ o leva a 41.", "++contador o leva a 42. Como são instruções separadas, a ordem está clara."],
        "Contadores acompanham tentativas de um jogo, posições de vetores e quantidade de registros. Confira o limite antes de usar o próximo índice.",
        "Após int i = 4; int anterior = i++; quais são os dois valores?",
        "anterior fica com 4 e i passa a valer 5."),
    "if": aprofundar(
        "Executar uma ação somente quando uma condição for atendida.",
        "A condição do if é avaliada uma vez a cada vez que o fluxo chega à instrução. O bloco entre chaves executa se o resultado for diferente de zero. Sem else, uma condição falsa apenas pula esse bloco. Escrever if (condicao); cria uma instrução vazia: o bloco seguinte deixa de depender do teste. Use chaves e confira separadamente o caso verdadeiro, o falso e os valores que ficam exatamente no limite.",
        ["O exemplo primeiro confere se a leitura de numero funcionou.", "Com 8, numero > 0 é verdadeiro e imprime Positivo. Com 0 ou -3, a comparação é falsa e essa mensagem não aparece."],
        "Uma operação como emprestar deve acontecer apenas depois de confirmar que o livro está disponível.",
        "Se a condição do if for falsa e não houver else, o programa inteiro termina?",
        "Não. Ele pula o bloco do if e continua na próxima instrução."),
    "else": aprofundar(
        "Definir dois caminhos exclusivos para a mesma decisão.",
        "else não recebe uma condição: ele cobre o que sobrou do if associado. Use uma regra que divida os casos do problema; se idade >= 18 é verdadeiro, o outro caminho corresponde a idade < 18. Isso não substitui validar se a idade faz sentido. Um else se liga ao if compatível mais próximo, e as chaves evitam uma associação diferente da imaginada.",
        ["O exemplo verifica idade >= 18.", "Apenas uma mensagem é mostrada: Maior de idade quando a comparação é verdadeira, ou Menor de idade no outro caminho."],
        "Na agenda, uma busca pode exibir o contato encontrado ou avisar que não existe um contato correspondente.",
        "Usar dois if separados garante que apenas um execute?",
        "Não. Os testes são independentes. if e else expressam explicitamente os dois caminhos de uma única decisão."),
    "else if": aprofundar(
        "Ordenar condições de classificação sem esconder casos.",
        "Uma cadeia termina na primeira condição verdadeira. Por isso, a ordem deve acompanhar a regra. Ao classificar notas, testar >= 7 antes de >= 9 faria uma nota 10 entrar no primeiro grupo. Confira os limites exatos, como 7 e 9, além dos valores entre eles. Valide uma faixa permitida antes da classificação quando o problema exigir notas de 0 a 10.",
        ["A nota 8 não atende >= 9, então o programa passa ao else if.", "Como 8 atende >= 7, imprime Conceito B e não executa o else final."],
        "O projeto de notas usa classificações; o jogo de adivinhação pode distinguir valor menor, maior ou igual ao alvo.",
        "Uma nota 9 deve entrar no teste >= 7 antes de >= 9?",
        "Não nessa classificação. Coloque >= 9 primeiro para preservar a categoria mais específica."),
    "switch": aprofundar(
        "Organizar escolhas discretas em um menu.",
        "switch recebe uma expressão de tipo inteiro ou enum. Cada case precisa de uma constante inteira; strings e faixas como 1 a 5 não são cases em C padrão. Depois de entrar em um case, a execução continua até break, return ou o fim do switch. default pode tratar uma opção desconhecida. O break encerra o switch mais próximo, não um laço externo que contém o menu.",
        ["A opção 2 seleciona case 2 e mostra Consultar.", "break impede que a execução atravesse os próximos casos. Uma opção sem case correspondente segue para default."],
        "Calculadora, cadastro e biblioteca podem organizar suas operações por opção de menu, com tratamento explícito para opção inválida.",
        "break dentro de um switch que está em um while encerra o while?",
        "Não. Ele encerra o switch; o laço externo continua de acordo com sua própria condição."),
    "ternário": aprofundar(
        "Escolher um valor usando uma condição curta.",
        "condicao ? valor_se_verdadeira : valor_se_falsa é uma expressão. Primeiro a condição é avaliada e depois apenas um dos dois caminhos é executado. O tipo final depende das regras de compatibilidade e conversão dos dois valores. Prefira o ternário para escolhas pequenas; tarefas com várias instruções ficam mais claras em if e else. Parênteses ajudam quando a expressão faz parte de uma conta maior.",
        ["a > b compara 17 e 42 e resulta em falso.", "A expressão escolhe b, então maior recebe 42 e esse valor é mostrado."],
        "Um relatório pode escolher um rótulo curto como disponível ou emprestado, sem espalhar a regra de empréstimo pela interface.",
        "O ternário calcula sempre os dois valores antes de escolher um?",
        "Não. Depois da condição, somente o caminho escolhido é avaliado."),
    "while": aprofundar(
        "Planejar início, condição de permanência e atualização de um laço.",
        "Antes de escrever um while, identifique o estado inicial, o que mantém a repetição e o que mudará esse estado. O teste acontece antes do corpo, então pode não haver nenhuma passagem. Em uma soma acumulada, separe o contador da variável total. Para ler entradas, uma falha de leitura precisa encerrar ou recuperar a entrada; repetir a mesma leitura inválida sem consumir dados pode prender o programa.",
        ["contador começa em 1; a condição contador <= 3 permite entrar.", "Cada passagem imprime um valor e incrementa contador. Quando chega a 4, o teste falha e o laço termina."],
        "Jogos e menus repetem ações enquanto a partida ou o atendimento está em andamento.",
        "Se contador já começar em 4 com condição contador <= 3, quantas linhas são impressas?",
        "Nenhuma. O primeiro teste já é falso."),
    "do while": aprofundar(
        "Usar uma repetição que precisa acontecer pelo menos uma vez.",
        "No do while, o corpo acontece antes do teste. Isso combina com apresentar um menu antes de decidir se o usuário quer continuar. A estrutura termina com ponto e vírgula depois de while(condicao). Ainda é necessário atualizar o estado e tratar entradas inválidas. A garantia de uma primeira passagem não significa que o programa deva aceitar o primeiro dado sem validá-lo.",
        ["O valor 1 é mostrado antes do primeiro teste.", "O incremento e o teste permitem mostrar 2 e 3. Depois do incremento para 4, a repetição termina."],
        "Uma calculadora ampliada pode apresentar o menu ao menos uma vez e repetir até a opção Sair.",
        "Qual é a principal diferença para while?",
        "do while executa o corpo antes do teste; while testa antes e pode executar zero vezes."),
    "for": aprofundar(
        "Percorrer uma sequência com limites claros.",
        "A inicialização acontece uma vez. Antes de cada passagem vem a condição; depois do corpo vem a atualização. for não faz contagem automática: você precisa escrever a atualização e escolher um limite válido. Para N elementos de um vetor, os índices usuais são 0 até N - 1, com condição i < N. A variável declarada no cabeçalho pertence ao escopo do laço.",
        ["i começa em 1 e o exemplo mostra seu valor enquanto i <= 5.", "Depois de cada linha, i++ prepara a próxima passagem. O teste com i igual a 6 encerra a execução."],
        "Listar contatos, percorrer livros e somar notas são percursos em que for deixa os limites visíveis.",
        "Em um vetor com cinco elementos, o índice 5 é válido?",
        "Não. Os índices vão de 0 a 4; a condição de percurso costuma ser i < 5."),
    "break": aprofundar(
        "Encerrar o laço ou switch mais próximo de forma previsível.",
        "break interrompe a estrutura mais interna entre laço e switch que o contém. Ele não encerra a função, nem todos os laços externos de uma só vez. Em uma busca, pode evitar trabalho depois que o item já foi encontrado. Cuidado para não abandonar recursos alocados ou arquivos abertos: a saída do laço deve levar a um trecho que finalize esses recursos.",
        ["O laço começa a mostrar os valores a partir de 1.", "Quando i chega a 6, break acontece antes do printf; por isso a saída contém apenas 1 2 3 4 5."],
        "Na agenda, a primeira correspondência pode encerrar uma busca quando a regra garante nomes únicos.",
        "break dentro de dois for aninhados encerra ambos?",
        "Não. Apenas o for mais interno é encerrado."),
    "continue": aprofundar(
        "Pular o restante da passagem sem perder a atualização do laço.",
        "continue não encerra o laço. Em for, o controle segue para a atualização e depois para o teste. Em while e do while, segue para a condição. Isso exige cuidado: se o incremento de um while estiver depois do continue, ele será pulado e o mesmo valor poderá ser processado indefinidamente. Use continue quando a rejeição de um caso deixar o fluxo mais claro.",
        ["O exemplo verifica se i é par usando o resto da divisão por 2.", "Os pares pulam o printf, mas o for ainda incrementa i. São mostrados 1 3 5."],
        "Um relatório pode ignorar registros que não atendem a um filtro sem interromper a listagem dos demais.",
        "Qual cuidado especial é necessário com continue em um while com contador?",
        "Garantir que o contador seja atualizado também nos caminhos que executam continue."),
    "criando função": aprofundar(
        "Separar uma tarefa com nome, entrada e resultado definidos.",
        "Uma função agrupa instruções para uma responsabilidade. A definição informa tipo do retorno, nome, parâmetros e corpo. A chamada fornece argumentos. Prefira nomes que expressem uma ação ou resultado, como calcularMedia. Decida se a função calcula um valor ou apenas o exibe; separar essas duas responsabilidades facilita testar o cálculo sem depender das mensagens do terminal.",
        ["dobro recebe um inteiro n e devolve n * 2.", "main chama dobro(5), recebe 10 e usa printf para exibir o resultado. A função não precisa conhecer a tela."],
        "Na calculadora, separe ler a operação, calcular e mostrar. Na agenda, separe cadastrar, buscar e listar.",
        "Uma função precisa usar printf para entregar um resultado?",
        "Não. Ela pode retornar o valor e deixar a exibição para quem a chamou."),
    "parâmetros": aprofundar(
        "Diferenciar argumento da chamada e parâmetro recebido.",
        "Em dobro(5), 5 é o argumento; na definição, n é o parâmetro. C passa valores por cópia. Alterar n não muda a variável usada como argumento por quem chamou. Quando um endereço é passado, o ponteiro também é copiado, mas permite alcançar o objeto original; essa técnica será aprofundada no módulo de ponteiros. Dê aos parâmetros nomes e tipos coerentes com sua responsabilidade.",
        ["O argumento 5 é copiado para n quando dobro começa.", "O cálculo usa essa cópia e retorna 10. A chamada pode ser repetida com outros valores sem reescrever a função."],
        "Uma função da agenda pode receber o vetor de contatos e a quantidade usada; uma função de cálculo recebe os valores necessários, sem depender de globais.",
        "Se uma função faz n = 0, a variável inteira original de quem chamou também muda?",
        "Não, quando ela foi passada por valor. A alteração atinge apenas o parâmetro local."),
    "retorno": aprofundar(
        "Comunicar um resultado e encerrar corretamente uma chamada.",
        "return encerra a função imediatamente. Em uma função que devolve int ou double, todos os caminhos de uso normal devem produzir um resultado compatível. Uma função void pode usar return; sem valor para encerrar cedo. Não devolva o endereço de uma variável local automática: o objeto deixa de existir depois da chamada. Retornar um valor não o imprime.",
        ["return n * 2 encerra dobro entregando o valor calculado.", "Quem chamou pode imprimir, armazenar ou usar esse resultado em outro cálculo."],
        "Operações de cadastro podem retornar sucesso ou falha; funções de busca podem retornar uma posição ou um indicador de não encontrado.",
        "O que acontece com as instruções que estão depois de um return já executado na mesma chamada?",
        "Elas não são executadas, pois a função já foi encerrada."),
    "protótipos": aprofundar(
        "Declarar a interface de uma função antes de chamá-la.",
        "O protótipo informa nome, tipo de retorno e tipos dos parâmetros. Ele permite ao compilador conferir a chamada mesmo quando a definição aparece depois. Declaração e definição precisam concordar. Em C11, int resposta(void) declara explicitamente ausência de parâmetros; int resposta() não fornece essa mesma informação em uma declaração. Em projetos com vários arquivos, coloque a interface compartilhada em um cabeçalho.",
        ["O protótipo de dobro aparece antes de main.", "main faz a chamada; a definição posterior contém o cálculo. O protótipo termina em ponto e vírgula, enquanto a definição contém um corpo."],
        "A calculadora pode oferecer funções em calculos.h e implementá-las em calculos.c, mantendo uma interface conferível.",
        "Declarar int dobro(int); já implementa o cálculo?",
        "Não. Essa linha descreve a interface. Ainda é necessário definir o corpo da função."),
    "recursão": aprofundar(
        "Reconhecer caso de parada e redução do problema.",
        "Uma função recursiva chama a si mesma para resolver uma parte menor do problema. É preciso haver um caso de parada e garantir que as chamadas se aproximem dele. Cada chamada usa recursos para seus parâmetros e estado; profundidade excessiva pode esgotar a pilha. Uma solução com laço pode ser mais adequada para entradas grandes. No fatorial, além de parar, é preciso restringir a entrada para o resultado caber no tipo escolhido.",
        ["fatorial(5) depende de 5 vezes fatorial(4), e assim por diante.", "O caso n <= 1 retorna 1 e permite concluir as chamadas pendentes: 2, 6, 24 e 120."],
        "O percurso de uma árvore usa recursão para visitar cada subárvore, com NULL como caso de parada.",
        "Ter um if de parada é suficiente se a chamada recursiva recebe sempre o mesmo n?",
        "Não. A entrada da chamada precisa avançar em direção ao caso de parada."),
    "arrays": aprofundar(
        "Guardar vários valores do mesmo tipo e percorrê-los sem ultrapassar seus limites.",
        "Um array reserva elementos consecutivos. Em int valores[3], os índices válidos são 0, 1 e 2: o tamanho não é um índice válido. C não verifica esses limites automaticamente. Ao passar o array para uma função, informe também sua quantidade de elementos; o parâmetro de array é ajustado para ponteiro e não transporta o tamanho. sizeof permite calcular a quantidade apenas onde o objeto ainda é um array completo.",
        ["valores contém 10, 20 e 30, nesta ordem.", "O laço acessa valores[i] enquanto i < 3. Usar i <= 3 tentaria acessar um quarto elemento inexistente."],
        "Cadastros e agendas podem começar com um array de capacidade fixa e uma variável separada para a quantidade ocupada.",
        "Um array de capacidade 100 que contém 7 contatos deve ter todos os 100 elementos consultados?",
        "Não. A busca deve percorrer apenas os 7 elementos preenchidos; capacidade e quantidade usada são informações diferentes."),
    "matrizes": aprofundar(
        "Organizar dados por linha e coluna e escolher os índices corretos.",
        "Uma matriz como int tabela[2][3] é um array de dois arrays com três inteiros cada. O primeiro índice seleciona a linha e o segundo seleciona a coluna. Dois laços permitem percorrer todas as posições, com limites independentes. Na memória, os elementos de cada linha ficam consecutivos. Ao criar uma função para receber a matriz, as dimensões necessárias ao cálculo dos endereços precisam ser conhecidas.",
        ["A matriz do exemplo tem duas linhas e duas colunas.", "A diagonal principal usa os mesmos índices para linha e coluna: matriz[0][0] + matriz[1][1] soma 10 e 32."],
        "Um jogo de terminal pode usar uma matriz como tabuleiro, validando linha e coluna antes de acessar uma casa.",
        "Em uma matriz [2][3], a posição [2][0] é válida?",
        "Não. As linhas válidas são 0 e 1; as colunas válidas são 0, 1 e 2."),
    "strings": aprofundar(
        "Distinguir texto, capacidade do array e marcador de fim.",
        "Em C, uma string é uma sequência de caracteres terminada por '\\0'. Esse byte indica onde o texto acaba, mesmo que o array tenha espaço sobrando. char nome[4] = \"Ana\" usa três posições para as letras e uma para o terminador. Um array de char sem terminador não é necessariamente uma string; passá-lo a printf com %s pode fazer a leitura ultrapassar o objeto. O tamanho em bytes pode ser diferente da quantidade de letras visíveis em textos UTF-8.",
        ["O literal Linguagem C já inclui o terminador ao inicializar o array.", "O laço imprime um caractere por vez e para ao encontrar '\\0', que não deve ser confundido com o caractere '0'."],
        "Nomes de pessoas, títulos de livros e textos do editor precisam reservar espaço para o terminador.",
        "Um array char texto[5] comporta a string \"cinco\"?",
        "Não. São cinco letras mais o terminador, portanto são necessárias pelo menos seis posições."),
    "strlen": aprofundar(
        "Medir o comprimento atual de uma string, sem confundir com a capacidade.",
        "strlen, declarada em string.h, conta os bytes anteriores ao primeiro '\\0' e retorna size_t. Use %zu para mostrar esse resultado. A função exige uma string válida: ela não recebe a capacidade para limitar sua procura. strlen(texto) não inclui o terminador; sizeof texto, quando texto é um array local completo, mede o armazenamento inteiro. Para percorrer uma string muito longa sem modificá-la, pode ser útil guardar o comprimento antes do laço.",
        ["compilar tem oito caracteres de um byte cada.", "strlen retorna 8, embora o array criado a partir do literal precise de nove bytes para incluir '\\0'."],
        "O editor usa comprimentos para verificar se uma operação de acrescentar texto cabe no buffer.",
        "Depois de copiar \"Oi\" para um array de 100 bytes, quanto strlen retorna?",
        "Retorna 2. Os 100 bytes representam a capacidade, não o comprimento do texto guardado."),
    "strcpy": aprofundar(
        "Copiar uma string quando a capacidade do destino foi comprovada.",
        "strcpy copia os caracteres e o terminador da origem para o destino. Ela não conhece o tamanho do destino e não impede uma cópia excessiva. O destino deve ter pelo menos strlen(origem) + 1 bytes, e as regiões não podem se sobrepor. Arrays não podem ser atribuídos com = depois da declaração como se fossem inteiros. strncpy não é uma substituição automaticamente segura: em alguns casos ela não produz o terminador.",
        ["destino tem capacidade 20, suficiente para C seguro e seu terminador.", "Após strcpy, destino contém uma cópia independente dos caracteres da origem."],
        "Ao guardar o nome em uma struct de cadastro, confira o limite antes da cópia ou use uma leitura limitada diretamente no campo.",
        "strcpy cria automaticamente mais espaço se a origem for maior?",
        "Não. É responsabilidade do programa garantir espaço suficiente antes de chamar a função."),
    "strcmp": aprofundar(
        "Comparar o conteúdo de duas strings pelo resultado da comparação.",
        "strcmp retorna zero quando os textos são iguais, um valor negativo quando o primeiro vem antes e um positivo quando vem depois na comparação dos bytes como unsigned char. Não dependa de resultados exatamente -1 ou 1. O operador == aplicado a ponteiros não compara o texto. A comparação diferencia maiúsculas de minúsculas e não implementa, por si só, regras de ordenação de nomes em português.",
        ["As duas strings casa são percorridas até que todos os bytes coincidam, incluindo o fim.", "O teste strcmp(a, b) == 0 entra no ramo que imprime Iguais."],
        "Uma agenda pode procurar um nome exato; para aceitar diferenças de maiúsculas ou acentos, é preciso definir outra política de comparação.",
        "Se strcmp devolve um número positivo, isso quer dizer que as strings são iguais?",
        "Não. Igualdade corresponde a zero. O sinal informa a ordem quando os conteúdos são diferentes."),
    "strcat": aprofundar(
        "Acrescentar texto sem perder o terminador ou ultrapassar o destino.",
        "strcat procura o fim da string de destino e copia a origem a partir dali, incluindo um novo terminador. O destino precisa já conter uma string válida e ter capacidade para os dois textos mais um byte. Para buffers pequenos de capacidade conhecida, verifique strlen(destino) + strlen(origem) + 1 <= capacidade. A função não aloca espaço, não recebe esse limite e não aceita regiões sobrepostas.",
        ["O destino começa com Curso e um espaço; a origem é de C.", "A concatenação substitui o terminador anterior pelos novos caracteres e deixa um terminador ao final de Curso de C."],
        "O editor deve recusar uma adição que exceda sua capacidade, mantendo o texto anterior intacto.",
        "Um destino sem texto pode ser usado em strcat sem inicialização?",
        "Não. Inicialize, por exemplo, com char texto[50] = \"\"; para que ele comece como uma string vazia válida."),
    "fgets": aprofundar(
        "Ler uma linha com espaços usando o limite do array.",
        "fgets recebe destino, capacidade e origem da leitura. Com capacidade positiva adequada, lê até capacidade - 1 caracteres, encontra uma quebra de linha ou chega ao fim da entrada, e termina a string em caso de sucesso. A quebra de linha fica no texto quando cabe. Retorno NULL exige tratamento antes de usar o buffer. Se uma linha for longa demais, o restante continua na entrada: remover '\\n' não descarta automaticamente esse restante.",
        ["A leitura usa sizeof nome para limitar a quantidade de bytes gravados.", "strcspn encontra a quebra de linha, quando existe; substituí-la por '\\0' evita uma linha extra ao cumprimentar."],
        "Use leitura por linha para nomes completos e títulos. Defina se uma linha excedente será rejeitada ou consumida, evitando que vire o próximo campo.",
        "Se a entrada for maior que o buffer, a próxima leitura sempre começa na próxima linha?",
        "Não. Pode começar no trecho que não coube; o programa precisa tratar essa situação."),
    "memória": aprofundar(
        "Distinguir o valor de um objeto, seu endereço e seu tempo de vida.",
        "Uma variável identifica um objeto que ocupa armazenamento durante determinado período. Um ponteiro guarda um endereço que pode permitir acesso a outro objeto; ele não é o próprio valor desse objeto. Variáveis locais automáticas existem durante sua execução no bloco, objetos estáticos duram toda a execução e objetos alocados dinamicamente duram até serem liberados. A organização exata dos endereços é do ambiente, portanto não dependa de um endereço fixo.",
        ["valor armazena um inteiro e p recebe seu endereço com &valor.", "*p acessa o inteiro existente nesse endereço; não cria uma segunda variável inteira independente."],
        "Na lista de cadastros, será necessário saber quem criou cada objeto e até quando os ponteiros para ele continuam válidos.",
        "É válido continuar usando o endereço de uma variável automática depois que a função terminou?",
        "Não. A vida daquele objeto terminou, mesmo que o endereço ainda pareça conter os mesmos bytes."),
    "operador &": aprofundar(
        "Obter um endereço e distinguir & de desreferenciamento.",
        "O operador unário & obtém o endereço de um objeto, e o operador unário * acessa o objeto apontado. Em int *p = &valor, o tipo indica que p aponta para int. Um ponteiro precisa referenciar um objeto válido antes de ser desreferenciado; NULL pode representar ausência, mas não pode ser usado com * para ler ou escrever. No scanf de um inteiro, &numero fornece o local onde o valor será armazenado.",
        ["&valor faz ponteiro apontar para o inteiro 42.", "printf usa *ponteiro para ler 42. Para mostrar o endereço, o formato seria %p com conversão para void *."],
        "Funções que preenchem campos de um cadastro recebem endereços dos objetos que devem modificar.",
        "Em p = &valor, o que muda se valor passar de 42 para 50?",
        "p continua apontando para o mesmo objeto, e *p passa a ler 50."),
    "ponteiros + funções": aprofundar(
        "Permitir que uma função modifique objetos de quem a chamou.",
        "C sempre passa argumentos por valor, inclusive ponteiros. Ao receber uma cópia do endereço, a função pode acessar o objeto original usando *. É assim que se implementa o efeito conhecido como passagem por referência. Mudar apenas o parâmetro ponteiro para outro endereço não muda o ponteiro do chamador. Documente quais ponteiros podem ser NULL e quais objetos serão modificados; use const quando o acesso deve ser somente de leitura.",
        ["trocar recebe os endereços de a e b, não apenas os inteiros 10 e 42.", "Uma variável temporária preserva o primeiro valor antes que *a e *b sejam atualizados."],
        "Emprestar um livro pode receber Livro *livro e alterar seu estado, devolvendo separadamente se a operação foi aceita.",
        "Por que trocar(int a, int b) não troca os inteiros originais?",
        "Porque altera apenas cópias locais. Receber os endereços permite acessar e modificar os objetos originais."),
    "ponteiros + arrays": aprofundar(
        "Relacionar índices e deslocamentos dentro de um array.",
        "Na maioria das expressões, o nome de um array é convertido em ponteiro para seu primeiro elemento. Para um índice válido, valores[i] equivale a *(valores + i). Somar 1 a um ponteiro avança um elemento do tipo apontado, não necessariamente um byte. A aritmética deve permanecer no mesmo array ou formar o endereço imediatamente após seu fim; esse último endereço pode servir de limite, mas não pode ser desreferenciado.",
        ["O ponteiro começa no primeiro elemento do array com 10, 20 e 12.", "Os deslocamentos 0, 1 e 2 acessam elementos válidos cuja soma é 42."],
        "Uma função de busca recebe ponteiro e quantidade, usando a quantidade para impedir acessos fora do cadastro.",
        "Um ponteiro para o fim do array pode ser usado com * para ler mais um elemento?",
        "Não. O endereço logo após o fim pode ser formado e comparado, mas não aponta para um elemento acessível."),
    "ponteiro para ponteiro": aprofundar(
        "Entender dois níveis de acesso e quando uma função precisa alterar um ponteiro.",
        "Em int **pp, pp aponta para um objeto do tipo int *. Se p aponta para valor e pp aponta para p, *pp acessa p e **pp acessa valor. Os dois níveis precisam estar válidos. Esse recurso permite a uma função atualizar o ponteiro do chamador, como o início de uma lista. Um int ** não é automaticamente compatível com uma matriz int[2][3]: as organizações de memória são diferentes.",
        ["p guarda &valor; pp guarda &p.", "A atribuição **pp = 42 atravessa os dois endereços e modifica o inteiro original."],
        "Ao inserir ou remover o primeiro nó de uma lista, receber No **inicio permite atualizar o início mantido pelo programa principal.",
        "O que *pp = outro faz, comparado com **pp = 42?",
        "A primeira operação altera o ponteiro p. A segunda altera o inteiro para o qual p aponta."),
    "malloc": aprofundar(
        "Solicitar armazenamento e conferir a falha antes de usá-lo.",
        "malloc, de stdlib.h, solicita uma quantidade de bytes e retorna um ponteiro ou NULL em caso de falha. A memória obtida não vem inicializada. Use sizeof *ponteiro para relacionar a quantidade ao tipo apontado e confira o retorno antes de escrever. Para vários elementos, valide a quantidade e evite que a multiplicação pelo tamanho transborde. Cada alocação bem-sucedida precisa de uma responsabilidade clara pela liberação.",
        ["malloc solicita espaço para um inteiro; o teste contra NULL protege o acesso seguinte.", "Depois de atribuir e usar 30, free libera o bloco. Não use o ponteiro para acessar esse bloco novamente."],
        "Na lista de contatos, cada inserção pode criar um nó. Se a alocação falhar, a lista existente deve continuar válida.",
        "malloc retorna um inteiro inicializado em zero?",
        "Não. Ela retorna um endereço e o conteúdo inicial do bloco não está definido para leitura como um inteiro inicializado."),
    "calloc": aprofundar(
        "Alocar vários elementos com os bytes inicialmente zerados.",
        "calloc recebe quantidade e tamanho de cada elemento, retornando NULL em caso de falha. Ela zera os bytes do armazenamento obtido; para os inteiros usados aqui isso representa zero. Não generalize essa representação para todo tipo, como ponteiros ou todos os formatos de ponto flutuante. A função facilita a inicialização de contadores, mas não dispensa a validação da quantidade, do retorno e dos índices.",
        ["calloc cria espaço para quatro inteiros, inicialmente com valor zero.", "Alterar somente o último para 42 mantém os três primeiros em zero; ao final o bloco é liberado."],
        "Uma tabela de contadores por categoria pode começar zerada, enquanto nomes e outros campos precisam de uma inicialização apropriada aos seus tipos.",
        "Por que ainda testar NULL depois de calloc?",
        "Porque zerar os bytes não garante que a alocação será possível. A solicitação pode falhar."),
    "realloc": aprofundar(
        "Mudar a capacidade de um bloco sem perder o endereço original em uma falha.",
        "realloc pode ampliar ou reduzir um bloco e pode movê-lo para outro endereço. Para um tamanho solicitado maior que zero, uma falha retorna NULL e mantém o bloco original válido. Por isso, guarde o retorno em um ponteiro temporário antes de substituir o original. Após sucesso, use apenas o novo ponteiro: referências antigas ao bloco podem ter ficado inválidas. A parte acrescentada não é inicializada. Evite tamanho zero para não depender de regras especiais.",
        ["O exemplo começa com dois inteiros e pede espaço para três.", "Se a solicitação der certo, o ponteiro é atualizado e o terceiro valor é inicializado antes de participar da soma."],
        "Um cadastro crescente separa quantidade usada e capacidade; aumenta a capacidade quando necessário e só confirma essa mudança após sucesso.",
        "Qual o risco de escrever dados = realloc(dados, novo_tamanho) diretamente?",
        "Em caso de falha, dados recebe NULL e o programa perde a referência ao bloco antigo, que continua alocado."),
    "free": aprofundar(
        "Encerrar a vida de um bloco alocado sem criar acessos inválidos.",
        "free deve receber NULL ou o endereço de um bloco ainda alocado obtido pelas funções de alocação. Não libere variáveis locais, posições internas de um bloco ou o mesmo bloco duas vezes. Depois da liberação, ler ou escrever por qualquer ponteiro que apontava para aquele bloco é inválido. Atribuir NULL ao ponteiro usado pode ajudar a evitar reutilização acidental, mas não atualiza outras cópias do endereço.",
        ["O inteiro alocado é conferido, preenchido e usado antes de free.", "Depois de free, atribuir NULL sinaliza que aquele ponteiro deixou de possuir um bloco válido."],
        "Remover um contato de uma lista exige ajustar os vínculos antes de liberar o nó removido.",
        "Depois de p = NULL, uma segunda variável q que guardava o mesmo endereço também vira NULL?",
        "Não. q continua com o endereço antigo e não deve ser usada para acessar o bloco liberado."),
    "memory leak": aprofundar(
        "Reconhecer caminhos de execução que abandonam memória ainda alocada.",
        "Um vazamento ocorre quando o programa deixa de liberar armazenamento de que não precisa mais, frequentemente perdendo sua referência. Em programas com muitas operações, esse desperdício se acumula. Revise todos os caminhos: sucesso, entrada inválida, falha intermediária, remoção e saída do menu. Definir um responsável por cada alocação reduz esquecimentos. A recuperação da memória pelo sistema quando o processo termina não substitui a liberação durante a execução.",
        ["executar solicita um inteiro e trata a falha antes de acessar o endereço.", "No caminho de sucesso, copia o resultado para uma variável antes de liberar o bloco e retornar."],
        "No sistema de biblioteca, remover um livro e encerrar o programa são caminhos diferentes que precisam liberar os nós correspondentes.",
        "Uma função que aloca em cada chamada, usa o bloco e retorna sem liberá-lo está correta porque o programa ainda funciona?",
        "Não. Sem transferir explicitamente a responsabilidade pelo bloco, esse caminho provoca um vazamento a cada chamada."),
    "structs": aprofundar(
        "Representar um registro com campos que descrevem a mesma entidade.",
        "Uma struct agrupa objetos de tipos possivelmente diferentes, como nome e idade de uma pessoa. Use . para acessar campos de um objeto e -> para campos por meio de um ponteiro. Uma atribuição entre structs do mesmo tipo copia seus campos, inclusive arrays internos; campos ponteiros continuam apontando para os mesmos objetos, sem duplicar automaticamente seus conteúdos. O compilador pode inserir espaçamento entre campos, então não calcule seu tamanho apenas somando os tamanhos individuais.",
        ["Pessoa reúne nome e idade em um único registro.", "Os acessos pessoa.nome e pessoa.idade selecionam campos diferentes do mesmo objeto."],
        "Cadastros, contatos e livros ficam mais organizados quando cada entidade possui um tipo com campos bem definidos.",
        "Copiar uma struct que contém um ponteiro cria uma nova cópia do bloco apontado?",
        "Não. Copia o endereço. Uma cópia independente do conteúdo exige alocação e cópia explícitas."),
    "typedef": aprofundar(
        "Dar um nome legível a um tipo sem criar armazenamento.",
        "typedef cria um nome alternativo para um tipo. Ele não cria uma variável, não aloca um registro e não transforma o tipo em uma classe. Em typedef struct { ... } Pessoa;, Pessoa passa a ser um nome de tipo utilizável nas declarações. Escolha nomes que expressem o domínio. Evite esconder ponteiros em nomes confusos, pois isso pode dificultar perceber quem modifica ou libera os objetos.",
        ["A declaração de Pessoa define como um registro será representado.", "A linha que declara a variável do tipo Pessoa é que cria o objeto usado para guardar Ana e sua idade."],
        "Tipos como Contato e Livro tornam as interfaces das funções de agenda e biblioteca mais fáceis de ler.",
        "typedef int Quantidade; já cria uma variável para contar livros?",
        "Não. Ele cria o nome de tipo Quantidade; ainda é preciso declarar uma variável desse tipo."),
    "unions": aprofundar(
        "Representar alternativas que compartilham o mesmo armazenamento.",
        "Em uma union, os membros compartilham armazenamento, ao contrário dos campos independentes de uma struct. Gravar um membro pode sobrescrever a representação de outro. Para um modelo simples e portátil, leia o membro que foi gravado e guarde separadamente uma indicação de qual alternativa está válida, normalmente um enum. Ler outro membro para interpretar os mesmos bytes depende da representação dos tipos e pode produzir valores inválidos; não use isso como conversão numérica.",
        ["O exemplo grava o membro inteiro com 10.", "A impressão lê esse mesmo membro; o campo de ponto flutuante não representa simultaneamente um segundo dado independente."],
        "Um registro de configuração pode guardar um inteiro ou um texto, acompanhado por um campo que indique qual alternativa está ativa.",
        "Uma union com idade e salario serve para guardar os dois valores independentes ao mesmo tempo?",
        "Não. Para preservar os dois simultaneamente, use uma struct."),
    "enum": aprofundar(
        "Dar nomes aos estados e opções inteiras de um programa.",
        "enum define constantes inteiras nomeadas. Sem valores explícitos, a primeira começa em zero e as seguintes aumentam de um em um. Os nomes ajudam a evitar números sem significado espalhados pelo programa. Ainda é necessário validar valores vindos do teclado ou de arquivos: declarar uma variável enum não garante que todo valor recebido corresponda a uma opção definida.",
        ["ABERTO recebe zero e FECHADO recebe um pela numeração automática.", "A variável guarda ABERTO; imprimir seu valor numérico mostra 0, mas o nome comunica melhor a intenção no código."],
        "A biblioteca pode usar DISPONIVEL e EMPRESTADO para expressar estados e validar as mudanças permitidas.",
        "Receber 9 do teclado é uma opção válida só porque será atribuído a um enum de duas opções?",
        "Não. Confira a entrada e aceite apenas os valores previstos."),
    "fopen": aprofundar(
        "Abrir um fluxo de arquivo escolhendo o modo e tratando a falha.",
        "fopen retorna FILE * ou NULL se a abertura falhar. O modo r lê um arquivo existente; w cria ou trunca, apagando o conteúdo anterior; a escreve no final. Modos com + permitem leitura e escrita, mas exigem cuidados adicionais ao alterná-las. Um caminho relativo é resolvido a partir do diretório de trabalho, não necessariamente da pasta do código. Permissões, caminho inexistente e recursos indisponíveis podem impedir a abertura.",
        ["O exemplo solicita a abertura de dados.txt no modo w.", "A mensagem de sucesso só aparece depois de conferir que o ponteiro não é NULL; o arquivo é fechado ao terminar."],
        "O cadastro precisa distinguir carregar dados existentes de criar um arquivo novo, para não apagar registros ao iniciar.",
        "Abrir um cadastro existente com w preserva os registros anteriores?",
        "Não. Esse modo trunca o arquivo. Para carregar registros existentes, comece com um modo de leitura apropriado."),
    "fclose": aprofundar(
        "Finalizar o uso de um arquivo e verificar o resultado da operação.",
        "fclose encerra o fluxo e descarrega dados de saída ainda no buffer. Seu retorno é zero em caso de sucesso e EOF em caso de erro. Uma gravação pode parecer concluída antes de os dados pendentes serem enviados; por isso, confira tanto a escrita quanto o fechamento. Depois de chamar fclose, não reutilize o FILE * para acessar o fluxo nem tente fechá-lo novamente, inclusive quando houve erro.",
        ["Depois de escrever no arquivo, o exemplo verifica o resultado de fclose.", "Arquivo fechado é mostrado no caminho em que o fechamento informa sucesso."],
        "Ao salvar a agenda, só confirme sucesso depois de conferir escrita e fechamento. Uma cópia de segurança deve preservar uma versão anterior válida.",
        "Se fprintf teve sucesso, é desnecessário verificar fclose?",
        "Não. O fechamento ainda pode detectar falhas ao descarregar a saída pendente."),
    "fprintf": aprofundar(
        "Gravar dados formatados em um fluxo de arquivo.",
        "fprintf funciona como printf, mas recebe o fluxo de destino como primeiro argumento. O retorno é a quantidade de caracteres produzidos ou um valor negativo se houver erro. Escolha um formato que possa ser lido novamente: defina separadores, regras para espaços, limites dos campos e quebras de linha. Não use texto recebido do usuário como string de formato. Salvar um arquivo não significa que seus dados persistirão em qualquer hospedagem: o ambiente também precisa oferecer armazenamento persistente.",
        ["O arquivo resultado.txt recebe Resposta: 42 por meio de fprintf.", "A mensagem do terminal é diferente do conteúdo gravado: printf envia para a saída padrão, enquanto fprintf usa o arquivo aberto."],
        "Para salvar contatos, escolha uma organização por registro e trate nomes que contenham o separador escolhido.",
        "fprintf(arquivo, nome) é adequado para gravar qualquer nome digitado?",
        "Não. Use fprintf(arquivo, \"%s\", nome), pois o conteúdo pode conter caracteres de formato, como %."),
    "fscanf": aprofundar(
        "Ler campos de arquivo conferindo quantas conversões deram certo.",
        "fscanf retorna a quantidade de conversões atribuídas, ou EOF se ocorre falha de entrada antes da primeira conversão. Não organize a leitura apenas com while (!feof(arquivo)): o fim é indicado depois de uma tentativa de leitura. Compare o retorno com a quantidade de campos esperada e trate registros inválidos. Em %s, use largura compatível com o destino. Para números externos fora de faixa e registros complexos, ler uma linha e convertê-la com strtol oferece mais controle.",
        ["O exemplo cria um arquivo com 19 e 23 e o reabre para leitura.", "A soma só é calculada quando fscanf confirma duas conversões; assim nenhuma variável é usada sem ter recebido um valor."],
        "Ao carregar uma biblioteca, um registro incompleto deve ser rejeitado ou sinalizado, sem acrescentar um livro parcialmente preenchido.",
        "Se o formato pede dois inteiros e fscanf retorna 1, é seguro somar os dois destinos?",
        "Não. Apenas um foi preenchido; o outro precisa ser tratado como não lido."),
    ".h": aprofundar(
        "Separar a interface pública das funções de sua implementação.",
        "Um cabeçalho reúne declarações compartilhadas: protótipos, tipos e constantes. #include insere seu conteúdo durante o pré-processamento. Em geral, não coloque definições de funções comuns nem variáveis globais com armazenamento em um cabeçalho incluído por vários .c, pois isso pode gerar definições duplicadas. Inclua no próprio cabeçalho o que ele precisa para que suas declarações sejam compreendidas.",
        ["A declaração de dobro antes de main representa a interface que poderia ficar em calculos.h.", "A definição que faz o cálculo representa a implementação. O exemplo reúne tudo em um arquivo para a prática do site."],
        "A calculadora pode expor somar e dividir em um cabeçalho, enquanto a biblioteca expõe buscar e emprestar sem espalhar detalhes internos.",
        "Incluir um cabeçalho com o protótipo já fornece o código executável da função?",
        "Não. A definição ainda precisa participar da compilação e da ligação."),
    ".c": aprofundar(
        "Distribuir implementações entre arquivos que serão compilados e ligados.",
        "Cada arquivo .c, após seus includes, forma uma unidade de tradução. Ele pode ser compilado em um arquivo objeto; depois, os objetos são ligados em um programa. Prefira incluir cabeçalhos em vez de incluir um .c dentro de outro. A implementação deve incluir seu próprio cabeçalho, permitindo conferir a concordância dos tipos. Funções auxiliares que não precisam ser acessadas por outros arquivos podem ser declaradas static.",
        ["O protótipo permite a chamada de triplo antes da definição.", "Separar a definição em outro .c não muda o resultado esperado, mas exige adicionar esse arquivo ao comando de compilação."],
        "No projeto final, entrada, cálculos e armazenamento podem ficar em módulos distintos com responsabilidades claras.",
        "Por que aparece referência indefinida se o protótipo existe, mas o .c da função ficou fora do build?",
        "Porque a declaração permitiu conferir a chamada, mas o ligador não recebeu a definição que implementa a função."),
    "include guards": aprofundar(
        "Impedir que o mesmo cabeçalho seja processado repetidamente em uma unidade de tradução.",
        "O padrão #ifndef, #define e #endif envolve o conteúdo de um cabeçalho. Na primeira inclusão, a macro é definida; nas seguintes, o conteúdo protegido é ignorado. Use um nome específico do projeto para evitar colisões. A proteção evita declarações de tipos repetidas dentro da mesma unidade, mas não resolve definições globais duplicadas entre vários arquivos .c. Cada unidade de tradução realiza seu próprio pré-processamento.",
        ["A macro de proteção começa indefinida e permite a declaração da função.", "Uma nova inclusão do mesmo cabeçalho na mesma unidade encontraria a macro definida e pularia o bloco."],
        "Se agenda.h e armazenamento.h incluem contato.h, a proteção evita processar duas vezes a definição de Contato na mesma compilação.",
        "Um include guard permite colocar uma variável global comum definida no cabeçalho sem risco de duplicação entre .c?",
        "Não. Para compartilhar uma variável, a declaração extern e uma única definição são questões separadas da proteção de inclusão."),
    "stdio": aprofundar(
        "Reconhecer os fluxos padrão e selecionar funções de entrada e saída.",
        "stdio.h declara FILE e funções como printf, scanf, fgets, fopen e fclose. stdin é a entrada padrão, stdout a saída padrão e stderr o fluxo usual de diagnósticos. Esses fluxos podem ser redirecionados e não representam sempre teclado e tela. A saída pode ficar em buffer; ao mostrar uma pergunta antes de ler, fflush(stdout) solicita o envio da saída pendente. fflush(stdin) não é uma forma portátil de limpar entrada em C.",
        ["fprintf recebe stdout explicitamente como destino.", "O resultado equivale a usar printf com o mesmo formato e argumento: Saida padrao: 42."],
        "Na calculadora interativa, separe perguntas, leitura, resultado e diagnóstico. Isso facilita testar tanto no terminal quanto com entrada preparada.",
        "stdin é obrigatoriamente o teclado físico do computador?",
        "Não. É um fluxo que pode vir de teclado, arquivo, redirecionamento ou do terminal oferecido pelo site."),
    "stdlib": aprofundar(
        "Usar conversão numérica controlada e conhecer os outros serviços da biblioteca.",
        "stdlib.h reúne alocação, conversão, ordenação e outras utilidades. Ao converter texto com strtol, use o ponteiro de fim para saber se houve dígitos e onde a conversão parou. Zere errno antes da chamada e confira ERANGE depois; em seguida valide a faixa exigida pelo seu programa antes de converter para um tipo menor. atoi não fornece esse mesmo conjunto de informações para distinguir entradas inválidas.",
        ["O exemplo converte a string 42 na base decimal.", "A conversão só é aceita se houve dígitos, não restou texto indevido e o resultado cabe no intervalo escolhido."],
        "Menus, idades e quantidades de livros podem ser lidos como linha e convertidos, permitindo recusar letras, excesso de caracteres e números grandes demais.",
        "strtol converter o começo de \"42abc\" significa que toda a entrada é válida?",
        "Não. O ponteiro de fim fica no a; é preciso decidir e validar o que pode existir depois do número."),
    "string": aprofundar(
        "Escolher entre operações de strings e operações de bytes.",
        "string.h declara funções de texto terminado em '\\0', como strlen e strcmp, e funções de memória, como memcpy e memmove, que recebem uma quantidade de bytes. memcpy exige regiões sem sobreposição; memmove admite sobreposição. Nenhuma delas conhece automaticamente o tamanho dos objetos. Uma função de bytes não acrescenta terminador por conta própria, e uma função de string precisa encontrar um terminador válido.",
        ["strcpy inicia o texto e strcat acrescenta 11 para formar C11.", "strcmp compara o resultado com C11; o teste com zero confirma a igualdade dos conteúdos."],
        "No editor, mover trechos dentro do mesmo buffer pode exigir memmove; concatenar exige conferir também o espaço para o terminador.",
        "Copiar três bytes com memcpy sempre produz uma string válida?",
        "Não. É necessário que o destino tenha espaço e que a representação final contenha um terminador apropriado."),
    "math": aprofundar(
        "Aplicar funções matemáticas verificando o domínio e a precisão.",
        "math.h declara funções como sqrt, pow e fabs. sqrt recebe um argumento não negativo para produzir uma raiz real; entradas fora do domínio precisam ser tratadas. Valores double têm precisão finita: não espere representação exata de todo decimal. Em muitos ambientes GCC, funções dessa biblioteca exigem -lm na ligação, após os fontes ou objetos que as utilizam. O include fornece declarações, não substitui a ligação da biblioteca.",
        ["sqrt recebe 25.0 e devolve 5.0.", "O formato com zero casas decimais apresenta 5; mudar a apresentação não transforma o valor armazenado em um inteiro."],
        "Uma calculadora ampliada pode oferecer raiz quadrada, recusando números negativos e deixando clara a precisão exibida.",
        "Adicionar #include <math.h> sempre resolve uma mensagem de referência indefinida a sqrt?",
        "Não. Também confira se a biblioteca matemática foi incluída corretamente na etapa de ligação do ambiente usado."),
    "bitwise": aprofundar(
        "Manipular bits individualmente sem confundir com operações lógicas.",
        "Os operadores &, |, ^ e ~ trabalham com bits de inteiros. Já &&, || e ! avaliam condições lógicas. Para manipulação de bits, prefira tipos unsigned e conheça sua largura. O deslocamento << move bits à esquerda e >> à direita; a quantidade deve ser não negativa e menor que a largura do operando promovido. Operações com inteiros negativos ou deslocamentos excessivos têm regras que não equivalem simplesmente a multiplicar e dividir.",
        ["21u representa um inteiro sem sinal; seus bits correspondem a 10101 em binário.", "Deslocar uma posição à esquerda produz 101010, que representa 42 e cabe no tipo usado."],
        "Permissões e conjuntos pequenos de opções podem ocupar bits de um único inteiro sem sinal.",
        "5 & 2 e 5 && 2 representam a mesma operação?",
        "Não. O primeiro combina bits e resulta em 0; o segundo verifica dois valores não nulos e resulta em 1."),
    "máscaras": aprofundar(
        "Consultar, ativar e desativar opções guardadas em bits.",
        "Uma máscara seleciona posições de bits. Defina opções independentes como potências de dois, por exemplo 1u << 0 e 1u << 1. flags & MASCARA consulta; flags |= MASCARA ativa; flags &= ~MASCARA desativa; flags ^= MASCARA alterna. Para exigir todos os bits de uma máscara composta, compare (flags & mascara) == mascara. Use parênteses para deixar clara a ordem dos operadores.",
        ["LER, ESCREVER e EXECUTAR ocupam bits diferentes.", "Combinar LER | EXECUTAR não ativa ESCREVER; o teste com & encontra o bit de execução."],
        "Uma versão ampliada da biblioteca pode reunir permissões de consultar e editar sem confundir autorização com o estado de empréstimo do livro.",
        "Usar ^ para desativar uma opção garante que ela ficará desligada?",
        "Não. ^ alterna: se estava desligada, fica ligada. Para desativar, use & com a máscara invertida."),
    "erros de sintaxe": aprofundar(
        "Ler o diagnóstico do compilador e corrigir a estrutura do código.",
        "Erros de sintaxe violam a gramática, como uma chave ou ponto e vírgula ausente. O diagnóstico costuma indicar arquivo, linha e uma posição aproximada; a causa pode estar na linha anterior. Comece pelo primeiro erro relevante, pois uma falha inicial pode produzir vários avisos posteriores. Avisos não devem ser ignorados só porque foi gerado um executável. Compilar sem erros também não prova que o programa resolve o problema correto.",
        ["A declaração de resposta termina em ponto e vírgula e o corpo de main está delimitado por chaves.", "Ao estudar localmente, remover e recolocar esse ponto e vírgula permite comparar o diagnóstico com a versão válida que imprime 42."],
        "Durante os projetos, compile após mudanças pequenas; assim é mais fácil localizar qual alteração introduziu um erro.",
        "A última linha citada pelo compilador é sempre o lugar onde o erro começou?",
        "Não. Uma chave, aspas ou comentário aberto anteriormente pode deslocar os diagnósticos para linhas seguintes."),
    "erros lógicos": aprofundar(
        "Comparar o comportamento observado com uma regra verificável.",
        "Um erro lógico ocorre quando o programa executa, mas produz um comportamento diferente do pretendido. Exemplos comuns são uma condição invertida, uma faixa incompleta, usar divisão inteira por engano ou percorrer um elemento a mais. Antes de alterar o código, escreva entrada e resultado esperado, acompanhe os valores e encontre a primeira divergência. Teste limites e casos vazios, não apenas o exemplo que deu certo.",
        ["As notas 8, 10 e 12 somam 30.", "Dividir pela quantidade correta produz média 10.00; usar outro divisor pode compilar normalmente e ainda assim estar errado."],
        "No sistema de biblioteca, emprestar um livro já emprestado é um erro de regra, mesmo que não gere erro de compilação.",
        "Process returned 0 garante que a média calculada está correta?",
        "Não. Esse código indica o encerramento informado pelo programa; a correção do resultado depende dos testes e da lógica."),
    "debug": aprofundar(
        "Observar o estado do programa para localizar a primeira divergência.",
        "Depurar é investigar uma execução. Um depurador permite pausar em pontos de parada, avançar por instruções e examinar variáveis e chamadas. Registros temporários também ajudam: mostre índice, entrada e resultado parcial com contexto. No GCC, -g inclui informações para depuração. Recursos de um depurador local não são automaticamente oferecidos pelo terminal do site. Remova saídas auxiliares antes de enviar um exercício cuja correção compara o texto produzido.",
        ["O exemplo mostra o índice e a soma parcial a cada passagem pelo array.", "Os totais 10, 30 e 42 permitem localizar em qual passo uma soma incorreta começaria."],
        "Para corrigir a agenda, acompanhe quantidade, posição procurada e nome comparado antes de mexer em várias funções ao mesmo tempo.",
        "Por que um programa com a conta correta pode falhar na comparação de saída depois de ser depurado?",
        "Porque mensagens extras de diagnóstico também fazem parte da saída capturada. Retire-as ou use o canal de diagnóstico adequado ao ambiente."),
    "gcc": aprofundar(
        "Transformar um arquivo C em programa e interpretar as opções básicas.",
        "GCC pode coordenar pré-processamento, compilação, montagem e ligação. Um comando de estudo é gcc -std=c11 -Wall -Wextra -pedantic main.c -o programa. -std escolhe a versão da linguagem; os avisos ajudam a encontrar construções suspeitas; -o escolhe o nome da saída. Depois execute o programa com o comando apropriado ao sistema. No Windows, é necessário ter uma distribuição do compilador instalada; um arquivo .exe não é o formato executável de todo sistema.",
        ["O código C do exemplo apenas imprime uma mensagem de confirmação.", "O comando de compilação é executado pelo ambiente externo, não como uma instrução escrita dentro de main."],
        "Nos projetos locais, registre o comando usado para que outra pessoa consiga reconstruir o mesmo programa a partir dos fontes.",
        "O comando gcc pertence ao código C que será colocado dentro de main?",
        "Não. Ele é um comando de terminal usado para construir o programa."),
    "linking": aprofundar(
        "Distinguir declaração conhecida de implementação disponível na ligação.",
        "A ligação combina arquivos objeto e bibliotecas, resolvendo referências entre eles. Uma função pode ter protótipo correto e ainda faltar sua definição, produzindo uma referência indefinida. Definir a mesma função externa em mais de um arquivo pode gerar definição múltipla. Com gcc -c arquivo.c, você gera um objeto sem executar a ligação final. A ordem das bibliotecas também pode importar, especialmente com bibliotecas estáticas.",
        ["O protótipo de resposta permite que main faça a chamada com tipos conhecidos.", "A definição que retorna 42 fornece a implementação que a ligação precisa encontrar."],
        "Ao separar o sistema de biblioteca, inclua todos os objetos necessários e evite duplicar main em arquivos que formarão o mesmo executável.",
        "Se só compilar main.c, que chama uma função definida em cadastro.c, o protótipo é suficiente para ligar o programa?",
        "Não. A definição de cadastro.c, ou seu arquivo objeto correspondente, também precisa participar."),
    "makefile": aprofundar(
        "Descrever alvos, dependências e comandos de construção.",
        "Um Makefile informa como produzir alvos a partir de dependências. Uma regra tem alvo: dependencias e, nas linhas seguintes, comandos de construção. Na forma padrão do GNU make, a receita começa com tabulação, não com espaços. make compara as dependências para decidir o que reconstruir. Cabeçalhos também devem ser considerados: modificar uma declaração pode exigir recompilar os .c que a usam. Makefile é um arquivo de construção, não código C.",
        ["O pequeno exemplo em C imprime um comando de compilação; imprimir o comando não o executa.", "O exemplo de vários arquivos abaixo apresenta um Makefile real. Execute make na pasta desses arquivos, em um ambiente local que tenha make e GCC."],
        "No projeto final modularizado, um comando de construção documentado evita esquecer arquivos e opções ao compilar.",
        "Alterar um .h sempre reconstrói um objeto se esse cabeçalho não está listado nem detectado como dependência?",
        "Não. O sistema de construção precisa conhecer essa relação para reconstruir corretamente."),
    "buffer overflow": aprofundar(
        "Evitar gravar além da capacidade de um objeto.",
        "Um buffer overflow é uma escrita além dos limites do armazenamento reservado. Isso pode corromper dados, causar falhas e criar riscos de segurança. Em strings, reserve o terminador; em arrays, valide índices antes do acesso. A largura de %s limita quantos caracteres scanf recebe, mas a função ainda lê apenas uma palavra e pode deixar o restante para depois. Prefira uma política explícita para linhas grandes e nunca use gets.",
        ["nome tem dez posições e o formato %9s reserva a décima para '\\0'.", "A impressão só ocorre quando uma conversão foi confirmada. Uma entrada longa ainda exige tratamento para o texto que ficou no fluxo."],
        "O editor deve recusar uma concatenação excessiva sem sobrescrever o buffer nem descartar silenciosamente o texto existente.",
        "Usar %10s em char nome[10] reserva espaço suficiente para o terminador?",
        "Não. Até dez caracteres podem ser lidos e ainda será necessário mais um byte. Nesse caso, a largura máxima é 9."),
    "validação": aprofundar(
        "Aceitar apenas entradas que atendam ao formato, à faixa e à regra do problema.",
        "Validar envolve camadas: a leitura aconteceu? O texto inteiro representa o tipo esperado? O valor cabe no tipo? Está na faixa permitida? A operação faz sentido no estado atual? Ler com fgets e converter com strtol permite conferir essas etapas separadamente. Defina também o que fazer com linhas longas, entrada encerrada e tentativas inválidas. Uma entrada rejeitada não deve deixar alterações parciais no cadastro.",
        ["O exemplo lê uma linha, verifica se ela coube e usa strtol para converter a idade.", "Só aceita a entrada após conferir dígitos, texto restante, erro de faixa e o intervalo de 0 a 120."],
        "Valide o contato inteiro antes de aumentar a quantidade; valide a disponibilidade do livro antes de confirmar um empréstimo.",
        "Um número bem convertido é necessariamente uma idade válida?",
        "Não. A conversão confirma a representação; ainda é preciso conferir a faixa e a regra do campo."),
    "listas": aprofundar(
        "Ligar nós e preservar o acesso à estrutura durante inserção e remoção.",
        "Uma lista encadeada guarda dados em nós ligados por ponteiros. O início aponta para o primeiro nó e NULL marca uma lista vazia ou o fim. Percorrer até uma posição exige seguir vínculos: não há acesso direto por índice como em um array. Inserções e remoções podem ser rápidas quando o ponto já é conhecido, mas a busca continua necessária. Ao liberar, guarde o próximo endereço antes de destruir o nó atual.",
        ["Cada alocação cria um nó e o vincula ao início, sem abandonar os nós anteriores.", "A limpeza salva o próximo ponteiro, libera o nó atual e continua até NULL, inclusive em caminhos de falha."],
        "Uma lista permite acrescentar contatos conforme a necessidade, com o custo de gerenciar alocação, busca e liberação de cada nó.",
        "Por que não se deve executar free(atual) e depois ler atual->proximo?",
        "Porque o nó já foi liberado. É necessário guardar proximo antes de chamar free."),
    "pilhas": aprofundar(
        "Implementar o comportamento de último a entrar, primeiro a sair.",
        "Uma pilha permite inserir e remover por uma mesma extremidade, chamada topo. Em um array, uma quantidade ocupada pode indicar onde inserir o próximo elemento; ao remover, confira se há elementos antes de diminuir essa quantidade. Pilha cheia e pilha vazia são estados normais que precisam de resposta definida, não de acesso fora do array. Quando a capacidade não muda, inserir e remover no topo são operações de tempo constante.",
        ["push confere a capacidade antes de guardar um valor e incrementar a quantidade.", "pop confere se a pilha está vazia e devolve o valor do último elemento inserido por um parâmetro de saída."],
        "Uma versão ampliada do editor pode guardar ações em uma pilha para desfazer primeiro a alteração mais recente.",
        "Depois de inserir 10 e 20, qual valor uma pilha deve remover primeiro?",
        "20, pois foi o último a entrar."),
    "filas": aprofundar(
        "Preservar a ordem de chegada reutilizando o armazenamento.",
        "Uma fila remove primeiro o elemento que entrou primeiro. Em um array circular, índices avançam com resto da divisão pela capacidade, voltando ao início quando necessário. Manter a quantidade ajuda a distinguir cheio e vazio mesmo quando índices coincidem. Confira esses estados antes de acessar. Se apenas aumentar índices sem reaproveitar posições, uma fila pode parecer cheia apesar de várias remoções anteriores.",
        ["A inserção calcula a posição após os elementos ocupados e aplica % CAPACIDADE.", "A remoção lê o início, avança esse índice circularmente e diminui a quantidade."],
        "Uma fila de reservas de livros deve atender a primeira pessoa que entrou, não a mais recente.",
        "Por que índices iguais não bastam, em toda representação, para distinguir fila cheia de vazia?",
        "Porque após uma volta completa eles podem coincidir nos dois estados; a representação precisa de quantidade ou outra convenção explícita."),
    "árvores": aprofundar(
        "Percorrer uma estrutura hierárquica reconhecendo suas condições de ordem.",
        "Uma árvore binária possui no máximo dois filhos por nó. Uma árvore binária de busca acrescenta uma regra de ordenação: valores menores ficam de um lado e maiores do outro, conforme uma política definida para duplicados. O percurso em ordem visita esquerda, nó e direita; ele produz valores ordenados somente quando a regra de busca é respeitada. A altura importa: uma árvore muito desequilibrada pode ter busca linear, não logarítmica.",
        ["A raiz 20 tem 10 à esquerda e 42 à direita.", "A função recursiva para quando recebe NULL e imprime 10, 20 e 42 ao visitar em ordem."],
        "Uma extensão do cadastro pode organizar registros por identificador, mas deve avaliar o custo de manter a árvore equilibrada.",
        "Toda árvore binária garante busca rápida em tempo logarítmico?",
        "Não. Sem controle da altura, ela pode se parecer com uma lista e exigir percorrer muitos nós."),
    "busca linear": aprofundar(
        "Procurar um valor percorrendo os elementos e tratar a ausência.",
        "A busca linear compara o alvo com cada elemento até encontrar uma ocorrência ou chegar ao fim. Funciona mesmo sem ordenação prévia. No melhor caso, a primeira comparação resolve; no pior, são necessárias n comparações para n elementos. Defina o resultado de não encontrado e a política para valores repetidos: primeira ocorrência ou todas. Em uma busca por nome, a comparação deve usar o conteúdo da string, não os endereços.",
        ["O exemplo compara o alvo 15 com 4, depois 8 e depois 15.", "Ao encontrar, informa o sucesso. Para um alvo ausente, é necessário um caminho de resposta diferente após terminar a procura."],
        "Na primeira versão da agenda, uma busca linear pelo nome é simples e suficiente para poucos contatos.",
        "Ordenar o array é um pré-requisito para a busca linear funcionar?",
        "Não. Ela percorre os elementos independentemente de sua ordem."),
    "bubble sort": aprofundar(
        "Ordenar por comparações e trocas entre elementos vizinhos.",
        "Bubble sort faz passagens pelo array comparando vizinhos e trocando pares fora de ordem. Ao final de uma passagem completa, o maior elemento da parte ativa chega à extremidade. As passagens seguintes podem reduzir o trecho comparado. Uma marca de troca permite encerrar cedo quando nada mudou. O custo no pior caso cresce quadraticamente, tornando o método útil para aprender, mas pouco adequado para grandes quantidades.",
        ["No array 3, 1, 2, trocar 3 com 1 e depois 3 com 2 leva o maior ao final.", "A verificação seguinte confirma 1, 2, 3 em ordem; os limites impedem comparar o último elemento com uma posição inexistente."],
        "Ao ordenar contatos, troque registros completos e não apenas os nomes, para não separar cada pessoa de seu telefone.",
        "Se os nomes forem ordenados sem mover os telefones correspondentes, o cadastro continua correto?",
        "Não. A associação entre os campos é parte do registro e precisa ser preservada."),
    "eficiência": aprofundar(
        "Relacionar tempo e memória à quantidade de dados, além de medir casos pequenos.",
        "Eficiência envolve trabalho realizado e memória usada. A notação O descreve como um limite de custo cresce com o tamanho da entrada, não um tempo exato em segundos. Percorrer n elementos uma vez costuma ser O(n); comparar muitos pares pode ser O(n²). Operações constantes, distribuição dos dados e ambiente influenciam medições reais. Primeiro assegure resultados corretos, depois meça casos representativos e escolha a estrutura adequada.",
        ["O exemplo verifica uma vez cada valor e conta três números pares.", "Aumentar a quantidade de elementos aumenta proporcionalmente o número de verificações, sem precisar comparar cada valor com todos os outros."],
        "No projeto final, compare busca e ordenação com diferentes quantidades de registros, mantendo os mesmos resultados antes de concluir que uma versão é melhor.",
        "Um programa que leva 1 ms com dez registros necessariamente continuará rápido com um milhão?",
        "Não. É preciso entender como o trabalho cresce e medir entradas maiores, além de considerar o uso de memória."),
    "calculadora": aprofundar(
        "Transformar operações isoladas em uma sequência de entrada, validação e resultado.",
        "Uma calculadora combina leitura dos operandos, escolha da operação, cálculo e apresentação. Separe essas responsabilidades para distinguir uma entrada inválida de uma operação impossível. A divisão exige testar o divisor antes de calcular. Defina se os operandos serão inteiros ou decimais e qual será a precisão exibida. Um menu repetido é uma ampliação: primeiro faça uma operação funcionar e depois acrescente repetição com uma opção de saída.",
        ["A função calcular recebe operandos e operador, retornando se a operação foi aceita.", "main valida a leitura e só imprime o resultado quando o cálculo informa sucesso; divisão por zero e operador desconhecido têm tratamento próprio."],
        "O exercício desta lição avalia um recorte da calculadora. O roteiro abaixo organiza uma ampliação sem mudar a saída exigida pelo exercício.",
        "Por que testar o divisor depois de executar a divisão é tarde demais?",
        "Porque a operação inválida já ocorreu. A condição deve impedir que o cálculo seja realizado."),
    "cadastro": aprofundar(
        "Manter registros válidos e controlar quantidade e capacidade.",
        "Um cadastro representa cada pessoa em uma struct e guarda vários registros em uma coleção. Capacidade é quanto cabe; quantidade é quanto já está preenchido. Valide um novo registro antes de inseri-lo, aumentando a quantidade apenas quando a operação terminar com sucesso. Defina um identificador que não dependa da posição: remover ou ordenar registros pode mudar índices. Busca, inclusão e listagem devem ter responsabilidades separadas.",
        ["adicionar verifica se existe espaço e se os campos respeitam os limites do modelo.", "A cópia do registro e o aumento da quantidade ocorrem juntos somente no caminho de sucesso."],
        "A agenda e a biblioteca reutilizam essa organização, substituindo os campos e as regras específicas de cada entidade.",
        "Deve-se aumentar a quantidade antes de validar o nome e a idade?",
        "Não. Isso poderia deixar um registro incompleto contado como válido."),
    "agenda": aprofundar(
        "Relacionar armazenamento, busca textual e uma resposta para cada resultado.",
        "Uma agenda associa nome e telefone no mesmo contato. Telefone é texto: pode conter prefixo, sinal de + e zeros iniciais que não representam uma quantidade para cálculos. A busca deve percorrer apenas contatos cadastrados e comparar nomes com strcmp conforme uma política definida. Se nomes podem repetir, um identificador evita ambiguidade ao editar ou excluir. Não encontrado é um resultado esperado e precisa ser apresentado sem acessar uma posição inválida.",
        ["buscar percorre os contatos válidos e retorna a posição do primeiro nome igual.", "main verifica se a posição não é negativa antes de acessar o telefone correspondente."],
        "Comece com busca exata e registros em memória. Depois adicione edição, remoção e persistência, mantendo cada operação testável.",
        "Por que armazenar um telefone em int pode perder informação?",
        "Porque zeros iniciais e símbolos fazem parte do texto, e o número completo também pode ultrapassar a faixa do tipo."),
    "jogo terminal": aprofundar(
        "Organizar um ciclo de tentativas com estado, regras e encerramento.",
        "Um jogo de adivinhação mantém um número secreto, recebe tentativas e informa se cada uma é menor, maior ou igual. Defina o intervalo válido, a contagem de tentativas e a condição de saída. Entradas inválidas não devem ser comparadas como se fossem palpites válidos. Use um segredo fixo durante os primeiros testes para repetir resultados; depois pode acrescentar sorteio. rand serve a exemplos simples, não a decisões que exigem segurança.",
        ["O laço recebe uma tentativa de cada vez e só compara quando a leitura foi válida.", "As respostas Maior, Menor e Acertou correspondem a estados diferentes; acertar encerra o laço."],
        "A mesma sequência de mostrar opções, ler, validar e atualizar estado aparece nos menus de cadastro e biblioteca.",
        "Como testar de forma repetível um jogo antes de adicionar sorteio?",
        "Use um segredo conhecido e sequências de tentativas menores, maiores e iguais, incluindo entradas inválidas e encerramento da entrada."),
    "sistema biblioteca": aprofundar(
        "Representar estados e permitir somente transições válidas.",
        "Um livro tem identidade, título e um estado, como disponível ou emprestado. Emprestar só é válido quando está disponível; devolver só é válido quando está emprestado. A função responsável deve conferir a condição antes de alterar o registro e informar sucesso ou falha. Buscar o livro, alterar seu estado e persistir o cadastro são etapas relacionadas, mas distintas. Em uma ampliação com usuários, também é necessário registrar quem retirou e impedir referências a pessoas inexistentes.",
        ["emprestar recebe o endereço do livro para alterar seu estado original.", "Uma segunda tentativa de empréstimo é recusada porque o estado já mudou; uma devolução válida o torna disponível novamente."],
        "O roteiro do projeto combina structs, busca, validação, funções e arquivos. A versão inicial pode usar apenas registros em memória.",
        "Alterar o estado antes de conferir se o livro existe é uma sequência segura?",
        "Não. Primeiro localize e valide o registro; somente depois aplique a transição permitida."),
    "editor texto": aprofundar(
        "Modificar texto mantendo a capacidade e o terminador como invariantes.",
        "Um editor simples pode começar com um buffer fixo, comprimento atual e operações de mostrar, acrescentar e limpar. Toda alteração deve preservar uma string terminada em '\\0' dentro da capacidade. Confira se a operação inteira cabe antes de escrever; uma recusa deve manter o texto anterior. Limpar pode ser tão simples quanto colocar '\\0' na primeira posição. Inserir e remover no meio exigem mover trechos corretamente, considerando sobreposição.",
        ["O exemplo soma os comprimentos do texto atual e do acréscimo, incluindo um byte para o terminador.", "strcat só é executada quando o conteúdo inteiro cabe; a saída mostra Aprender C."],
        "Amplie primeiro com leitura por linha e salvamento. Desfazer, capacidade dinâmica e edição no meio são etapas posteriores, não exigências implícitas do exercício.",
        "Por que truncar silenciosamente o texto pode ser ruim mesmo sem ultrapassar o buffer?",
        "Porque evita a escrita indevida, mas perde conteúdo sem avisar. O projeto precisa de uma política clara de recusa ou truncamento informado."),
    "projeto final": aprofundar(
        "Integrar conceitos em um programa com requisitos claros e testes reproduzíveis.",
        "Um projeto final deve definir o problema, entradas aceitas, operações, saídas e critérios de sucesso. Construa uma versão pequena que funcione de ponta a ponta e amplie em etapas. Separe representação dos dados, regras e interação com o usuário. Trate erros de leitura, limites, recursos e arquivos sem corromper o estado anterior. Documente como compilar e testar, incluindo dados de exemplo e resultados esperados, para que outra pessoa consiga repetir a demonstração.",
        ["A função de média recebe os dados e a quantidade, recusando uma coleção vazia.", "O exemplo testa a parte central do cálculo; menu, leitura e salvamento são responsabilidades a acrescentar separadamente."],
        "O exercício avaliado usa uma parte objetiva do projeto. Para uma entrega completa, reúna também organização, justificativa das escolhas e evidências de testes no roteiro abaixo.",
        "O que vale mais como evidência de conclusão: o programa abrir ou seus requisitos passarem por testes conhecidos?",
        "Os requisitos verificados por testes. Abrir e compilar são necessários, mas não demonstram sozinhos que entradas, operações e resultados estão corretos."),
}
