"""Conteudo pedagogico especifico para as licoes da trilha de C."""


def plano(teoria, fundamento, cuidado, desafio, termos, saida=None, entrada=None):
    correcao = {"codigo_contem": termos, "saida_obrigatoria": True}
    if entrada is not None:
        correcao["testes"] = [{"entrada": entrada, "saida_contem": saida or []}]
    elif saida:
        correcao["saida_contem"] = saida

    return {
        "teoria": teoria,
        "fundamento": fundamento,
        "cuidado": cuidado,
        "desafio": desafio,
        "correcao": correcao,
    }


PLANOS_LICOES = {
    "O que é C": plano(
        "C é uma linguagem compilada, procedural e próxima do hardware. O código-fonte é traduzido para código de máquina antes da execução, o que favorece desempenho e controle sobre memória. Ela é usada em sistemas operacionais, embarcados, bibliotecas e aplicações que precisam de eficiência.",
        "Um programa C precisa ser compilado antes de virar um executável.",
        "C oferece controle, mas não impede automaticamente acessos inválidos à memória.",
        'Crie um programa que mostre exatamente "Comecei em C" e termine com código de sucesso.',
        ["main", "printf", "return 0"],
        ["Comecei em C"],
    ),
    "Estrutura básica": plano(
        "Um arquivo C costuma reunir diretivas do pré-processador, declarações e funções. A execução começa em main; as chaves delimitam blocos e o ponto e vírgula encerra a maioria das instruções. Indentação não muda o resultado, mas torna a estrutura visível.",
        "A função main é o ponto de entrada e retorna um status ao sistema operacional.",
        "Esquecer chaves, parênteses ou ponto e vírgula costuma gerar erros em linhas próximas.",
        'Monte a estrutura completa de um programa e imprima duas linhas: "Inicio" e "Fim".',
        ["#include <stdio.h>", "int main", "printf", "return 0"],
        ["Inicio", "Fim"],
    ),
    "Comentários": plano(
        "Comentários documentam decisões sem serem executados. Use // para uma linha e /* ... */ para um bloco. Bons comentários explicam a intenção ou uma restrição; repetir literalmente o comando cria ruído e envelhece rápido.",
        "Comentários são removidos durante o processamento e não alteram a saída do programa.",
        "Um comentário de bloco não terminado faz o compilador ignorar o restante do arquivo.",
        'Use os dois formatos de comentário e faça o programa mostrar "Comentarios OK".',
        ["//", "/*", "*/", "printf"],
        ["Comentarios OK"],
    ),
    "Compilação": plano(
        "A construção de um programa passa por pré-processamento, compilação, montagem e ligação. Mensagens de erro impedem o executável; avisos indicam situações suspeitas. Leia primeiro a primeira mensagem, porque erros posteriores podem ser consequência dela.",
        "Compilar transforma o código-fonte e resolve referências necessárias para criar o executável.",
        "Ignorar warnings pode esconder conversões incorretas, variáveis não usadas e outros defeitos.",
        'Escreva um programa sem warnings óbvios que calcule 6 * 7 e mostre "Resultado: 42".',
        ["int main", "*", "printf", "return 0"],
        ["Resultado: 42"],
    ),
    "printf": plano(
        "printf envia texto formatado para a saída padrão. O formato descreve como cada argumento será exibido: %d para int, %.2f para decimal com duas casas, %c para caractere e %s para string. Cada especificador precisa corresponder ao tipo do argumento.",
        "O texto de formato e os argumentos devem ter tipos e quantidade compatíveis.",
        "Usar %d para um double ou esquecer um argumento produz comportamento indefinido.",
        'Declare idade 20, altura 1.75 e inicial A; mostre "Idade: 20 | Altura: 1.75 | Inicial: A".',
        ["int", "double", "char", "%d", "%.2f", "%c", "printf"],
        ["Idade: 20", "Altura: 1.75", "Inicial: A"],
    ),
    "scanf": plano(
        "scanf lê dados seguindo um formato. Para tipos escalares, passe o endereço da variável com &: assim a função pode gravar no local correto. O retorno informa quantos campos foram lidos e deve ser conferido para rejeitar entradas incompatíveis.",
        "O operador & fornece a scanf o endereço onde o valor será armazenado.",
        "Não validar o retorno de scanf pode deixar variáveis sem um valor confiável.",
        "Leia dois inteiros, valide a leitura e mostre a soma no formato \"Soma: N\".",
        ["scanf", "&", "== 2", "+", "printf"],
        ["Soma: 12"],
        "5 7\n",
    ),
    "int": plano(
        "int representa números inteiros dentro de uma faixa dependente da implementação, normalmente 32 bits. Declare a variável antes de usar, inicialize-a e escolha nomes que expressem sua função. Operações entre int descartam a parte fracionária.",
        "Uma variável int deve ser inicializada antes de participar de cálculos.",
        "Somar valores além da faixa de int causa overflow e resultado não confiável.",
        "Declare quantidade 8 e precoUnitario 15; calcule e mostre \"Total: 120\".",
        ["int", "*", "printf"],
        ["Total: 120"],
    ),
    "float e double": plano(
        "float e double armazenam aproximações de números reais. double geralmente oferece mais precisão e é a escolha padrão para cálculos decimais. Em printf, ambos usam %f; em scanf, float usa %f e double usa %lf.",
        "double preserva mais dígitos significativos que float na maioria das plataformas.",
        "Comparar decimais calculados com == pode falhar por causa da representação binária.",
        "Calcule a média double de 7.5, 8.0 e 9.5 e mostre com duas casas.",
        ["double", "/ 3.0", "%.2f", "printf"],
        ["8.33"],
    ),
    "char": plano(
        "char guarda um pequeno valor inteiro e é usado para representar caracteres. Literais de caractere usam aspas simples, como 'A'. A codificação mais comum é ASCII, na qual letras e dígitos possuem valores numéricos conhecidos.",
        "Um caractere usa aspas simples; uma string usa aspas duplas.",
        "Guardar 'AB' em char não cria uma palavra e tem significado dependente da implementação.",
        "Declare a letra 'C' e mostre o caractere e seu código numérico.",
        ["char", "'C'", "%c", "%d", "printf"],
        ["C", "67"],
    ),
    "constantes": plano(
        "Uma constante nomeada com const não deve ser alterada depois da inicialização. Ela documenta valores fixos, permite verificação de tipo e evita números mágicos espalhados pelo programa. O compilador pode impedir atribuições acidentais.",
        "const cria um objeto tipado que o código não deve modificar.",
        "Repetir um valor literal em vários pontos dificulta manutenção e revisão.",
        "Crie a constante DIAS_SEMANA com valor 7 e mostre \"Duas semanas: 14 dias\".",
        ["const int", "DIAS_SEMANA", "* 2", "printf"],
        ["Duas semanas: 14 dias"],
    ),
    "#define": plano(
        "#define cria uma substituição realizada pelo pré-processador antes da compilação. É útil para constantes simbólicas e macros simples, mas não possui tipo. Coloque parênteses em macros com parâmetros para preservar a ordem das operações.",
        "Uma macro é expandida como texto durante o pré-processamento.",
        "Uma macro como QUADRADO(x) x*x falha em expressões como QUADRADO(1+2).",
        "Defina a macro DOBRO(x) com parênteses e mostre o dobro de 21.",
        ["#define DOBRO", "((x) * 2)", "DOBRO(21)", "printf"],
        ["42"],
    ),
    "escopo": plano(
        "Escopo determina onde um identificador pode ser usado. Variáveis locais existem dentro do bloco em que foram declaradas; globais são visíveis a várias funções e vivem durante todo o programa. Prefira o menor escopo possível para reduzir dependências.",
        "Uma variável local declarada em um bloco não pode ser acessada fora dele.",
        "Globais mutáveis facilitam efeitos colaterais e tornam testes mais difíceis.",
        "Crie uma constante global LIMITE e uma variável local valor; mostre \"Dentro do limite\" quando valor for menor.",
        ["const int LIMITE", "int valor", "if", "printf"],
        ["Dentro do limite"],
    ),
    "soma": plano(
        "O operador + soma valores numéricos. O tipo do resultado depende dos operandos: int + int produz int, enquanto a presença de double promove a operação. Parênteses deixam clara a ordem quando a soma participa de uma expressão maior.",
        "A conversão dos operandos acontece antes de a soma ser calculada.",
        "Somar caracteres ou misturar tipos sem intenção pode produzir resultados surpreendentes.",
        "Some 18 e 24 em uma terceira variável e mostre \"Soma: 42\".",
        ["+", "int", "printf"],
        ["Soma: 42"],
    ),
    "subtração": plano(
        "O operador - calcula diferença e também pode representar sinal negativo. Em valores unsigned, um resultado abaixo de zero dá a volta na faixa do tipo. Use tipos com sinal quando diferenças negativas fizerem sentido.",
        "Subtração entre inteiros com sinal pode gerar um resultado negativo.",
        "Subtrair um valor maior de um unsigned não produz um número negativo.",
        "Calcule o saldo após retirar 58 de 100 e mostre \"Saldo: 42\".",
        ["-", "int", "printf"],
        ["Saldo: 42"],
    ),
    "multiplicação": plano(
        "O operador * multiplica dois valores. Não confunda seu uso aritmético com a declaração ou desreferência de ponteiros; o contexto define o significado. Verifique a faixa do tipo antes de multiplicar números grandes.",
        "A multiplicação é feita no tipo resultante das conversões dos operandos.",
        "O resultado pode sofrer overflow antes de ser atribuído a uma variável maior.",
        "Calcule 6 vezes 7 e mostre \"Produto: 42\".",
        ["6 * 7", "printf"],
        ["Produto: 42"],
    ),
    "divisão": plano(
        "Divisão entre inteiros produz apenas a parte inteira: 5 / 2 resulta em 2. Para preservar a fração, pelo menos um operando deve ser float ou double. O divisor precisa ser validado para nunca ser zero.",
        "Converter um operando para double muda a operação para divisão real.",
        "Divisão por zero é inválida; em inteiros pode encerrar o programa.",
        "Leia dividendo e divisor, rejeite zero e mostre o resultado com duas casas.",
        ["scanf", "divisor != 0", "(double)", "/", "%.2f"],
        ["Resultado: 3.50"],
        "7 2\n",
    ),
    "operadores relacionais": plano(
        "Os operadores <, <=, >, >=, == e != comparam dois valores e produzem 0 ou 1. Use == para comparação; = realiza atribuição. Comparações podem ser combinadas com decisões e repetições.",
        "O resultado de uma comparação em C é falso (0) ou verdadeiro (valor não zero).",
        "Escrever if (x = 5) altera x e quase sempre cria um erro lógico.",
        "Compare 42 e 30 e mostre os resultados de maior, igual e diferente como 1, 0 e 1.",
        [">", "==", "!=", "printf"],
        ["1 0 1"],
    ),
    "operadores lógicos": plano(
        "&& exige que as duas condições sejam verdadeiras, || exige pelo menos uma e ! inverte o valor lógico. C usa curto-circuito: a segunda parte pode não ser avaliada. Isso permite validar um ponteiro antes de acessá-lo.",
        "Em A && B, B não é avaliada quando A já é falsa.",
        "Usar & no lugar de && muda a operação para bit a bit e remove o curto-circuito.",
        "Com idade 20 e documento 1, use && para mostrar \"Entrada permitida\".",
        ["&&", "if", "printf"],
        ["Entrada permitida"],
    ),
    "incremento": plano(
        "++ e -- alteram uma variável em uma unidade. Na forma prefixa, a alteração ocorre antes de o valor participar da expressão; na pós-fixa, depois. Em comandos isolados, i++ e ++i têm o mesmo efeito.",
        "Use incremento principalmente como comando claro de controle de contadores.",
        "Modificar a mesma variável várias vezes na mesma expressão pode causar comportamento indefinido.",
        "Comece contador em 40, incremente duas vezes e mostre \"Contador: 42\".",
        ["++", "int contador", "printf"],
        ["Contador: 42"],
    ),
    "if": plano(
        "if executa um bloco quando sua expressão é diferente de zero. A condição deve representar diretamente a regra do problema. Chaves são recomendadas mesmo em blocos de uma linha porque evitam erros durante futuras alterações.",
        "Somente o bloco associado a uma condição verdadeira é executado.",
        "Um ponto e vírgula logo após if cria um bloco vazio e quebra a decisão.",
        "Leia um número e mostre \"Positivo\" apenas quando ele for maior que zero.",
        ["scanf", "if", "> 0", "printf"],
        ["Positivo"],
        "8\n",
    ),
    "else": plano(
        "else define o caminho executado quando a condição do if é falsa. Ele não recebe condição própria e sempre se associa ao if compatível mais próximo. Organize as chaves e a indentação para deixar essa associação evidente.",
        "if e else representam dois caminhos mutuamente exclusivos.",
        "Condições sobrepostas em blocos separados podem imprimir respostas contraditórias.",
        "Leia a idade e mostre \"Maior de idade\" ou \"Menor de idade\".",
        ["scanf", "if", "else", "printf"],
        ["Menor de idade"],
        "16\n",
    ),
    "else if": plano(
        "Uma cadeia if, else if e else seleciona a primeira condição verdadeira. Ordene as condições do caso mais específico para o mais geral. Quando uma faixa é atendida, as demais não são verificadas.",
        "A ordem das condições altera qual classificação será escolhida.",
        "Testar primeiro uma condição ampla pode tornar as condições seguintes inalcançáveis.",
        "Leia uma nota e classifique: A para >= 9, B para >= 7 e C nos demais casos.",
        ["scanf", "else if", ">= 9", ">= 7", "printf"],
        ["B"],
        "8\n",
    ),
    "switch": plano(
        "switch compara uma expressão inteira com valores constantes de case. break evita que a execução continue no próximo caso; default trata valores não previstos. É apropriado para menus e estados discretos.",
        "Sem break, a execução continua pelos cases seguintes, comportamento chamado fall-through.",
        "case não aceita intervalos ou expressões avaliadas em tempo de execução.",
        "Leia uma opção de 1 a 3 e mostre \"Cadastrar\", \"Consultar\" ou \"Sair\"; trate outras como inválidas.",
        ["scanf", "switch", "case 1", "case 2", "case 3", "default", "break"],
        ["Consultar"],
        "2\n",
    ),
    "ternário": plano(
        "O operador condicional condição ? valor1 : valor2 escolhe uma de duas expressões. É útil para decisões curtas que produzem um valor. Quando a regra exige várias ações, if e else são mais legíveis.",
        "O ternário é uma expressão e pode ser usado na inicialização de uma variável.",
        "Aninhar muitos ternários reduz rapidamente a legibilidade.",
        "Use o ternário para guardar o maior entre 17 e 42 e mostre \"Maior: 42\".",
        ["?", ":", "printf"],
        ["Maior: 42"],
    ),
    "while": plano(
        "while testa a condição antes de cada repetição, portanto pode executar zero vezes. Ele é indicado quando a quantidade de repetições depende de um estado. O corpo precisa alterar algo que permita encerrar o laço.",
        "A condição é avaliada antes da primeira execução do bloco.",
        "Esquecer de atualizar o estado usado na condição cria um laço infinito.",
        "Use while para somar os números de 1 a 6 e mostre \"Soma: 21\".",
        ["while", "++", "+=", "printf"],
        ["Soma: 21"],
    ),
    "do while": plano(
        "do while executa o bloco antes de testar a condição, garantindo ao menos uma passagem. É útil em menus ou validações que precisam solicitar um valor antes de decidir repetir. A estrutura termina com ponto e vírgula.",
        "O corpo de do while sempre executa pelo menos uma vez.",
        "Esquecer o ponto e vírgula depois de while causa erro de sintaxe.",
        "Use do while para imprimir 1, 2 e 3, cada número em uma linha.",
        ["do", "while", "++", "printf"],
        ["1", "2", "3"],
    ),
    "for": plano(
        "for reúne inicialização, condição e atualização no cabeçalho. É ideal para percursos com contador conhecido e para arrays. A variável de controle pode ser declarada no próprio laço em C99 ou mais recente.",
        "As três partes do for controlam início, permanência e avanço da repetição.",
        "Usar <= ao percorrer um array de tamanho N acessa a posição inválida N.",
        "Use for para mostrar os quadrados de 1 a 5 na mesma linha.",
        ["for", "i * i", "printf"],
        ["1 4 9 16 25"],
    ),
    "break": plano(
        "break encerra imediatamente o laço ou switch mais interno. Ele é útil quando o objetivo já foi encontrado e continuar seria desperdício. O fluxo segue na primeira instrução após a estrutura.",
        "break afeta apenas a estrutura de repetição ou switch que o contém diretamente.",
        "Usar break em excesso pode esconder uma condição de parada mal planejada.",
        "Percorra 1 a 10, interrompa ao chegar em 6 e imprima apenas 1 a 5.",
        ["for", "break", "i == 6", "printf"],
        ["1 2 3 4 5"],
    ),
    "continue": plano(
        "continue pula o restante da iteração atual e volta ao teste ou atualização do laço. É útil para ignorar elementos inválidos sem criar um bloco if muito profundo.",
        "Em for, continue segue para a expressão de atualização antes do próximo teste.",
        "Em while, pular a atualização do contador pode causar laço infinito.",
        "Mostre os números de 1 a 9, ignorando os múltiplos de 3 com continue.",
        ["for", "continue", "% 3", "printf"],
        ["1 2 4 5 7 8"],
    ),
    "criando função": plano(
        "Uma função agrupa uma responsabilidade com nome, tipo de retorno e parâmetros. Funções curtas reduzem repetição e permitem testar partes do programa isoladamente. main deve coordenar o fluxo, não concentrar toda a lógica.",
        "A assinatura informa nome, parâmetros e tipo do valor devolvido.",
        "Copiar a mesma lógica em vários pontos aumenta o custo de correção.",
        "Crie a função exibirMensagem(void) e use-a para mostrar \"Funcao chamada\".",
        ["void exibirMensagem(void)", "exibirMensagem();", "printf"],
        ["Funcao chamada"],
    ),
    "parâmetros": plano(
        "Parâmetros recebem os argumentos enviados na chamada. Em C, valores escalares são copiados; alterar o parâmetro não altera a variável original. Tipos e ordem dos argumentos precisam corresponder à assinatura.",
        "Passagem por valor cria uma cópia local de cada argumento escalar.",
        "Trocar a ordem de argumentos do mesmo tipo pode compilar e ainda produzir lógica errada.",
        "Crie soma(int a, int b), chame com 19 e 23 e mostre o resultado.",
        ["int soma(int a, int b)", "soma(19, 23)", "return a + b", "printf"],
        ["42"],
    ),
    "retorno": plano(
        "return encerra a função e, quando o tipo não é void, entrega um valor ao chamador. Todos os caminhos de uma função não void devem retornar um valor compatível. O resultado pode ser armazenado ou usado em outra expressão.",
        "O tipo declarado da função deve ser compatível com o valor retornado.",
        "Chegar ao fim de uma função não void sem return produz comportamento indefinido.",
        "Crie a função quadrado que retorna o quadrado de um int e mostre quadrado(7).",
        ["int quadrado", "return", "quadrado(7)", "printf"],
        ["49"],
    ),
    "protótipos": plano(
        "Um protótipo declara a assinatura antes da implementação. Assim o compilador verifica chamadas mesmo quando a definição aparece depois de main. Cabeçalhos normalmente reúnem protótipos compartilhados.",
        "O protótipo e a definição precisam ter tipos e parâmetros compatíveis.",
        "Declarar uma assinatura diferente da definição gera conflito de tipos.",
        "Declare o protótipo dobro(int), chame a função em main e implemente-a depois de main.",
        ["int dobro(int", "int main", "dobro(21)", "return n * 2"],
        ["42"],
    ),
    "recursão": plano(
        "Recursão ocorre quando uma função chama a si mesma com um problema menor. Toda solução recursiva precisa de caso-base e progresso em direção a ele. Cada chamada ocupa espaço na pilha.",
        "O caso-base encerra a cadeia de chamadas recursivas.",
        "Sem caso-base alcançável, a pilha cresce até o programa falhar.",
        "Implemente fatorial recursivo e mostre o resultado para 5.",
        ["fatorial(n - 1)", "if", "return", "fatorial(5)"],
        ["120"],
    ),
    "arrays": plano(
        "Um array armazena elementos do mesmo tipo em posições contíguas. Os índices começam em zero e terminam em tamanho - 1. Ao passar para uma função, o array normalmente é convertido em ponteiro para o primeiro elemento.",
        "Um vetor de tamanho N possui índices válidos de 0 a N - 1.",
        "Acessar fora dos limites é comportamento indefinido e pode corromper memória.",
        "Crie um vetor {4, 8, 15, 16, 23, 42}, some os elementos e mostre 108.",
        ["int valores[6]", "for", "valores[i]", "+=", "printf"],
        ["108"],
    ),
    "matrizes": plano(
        "Uma matriz em C é um array cujos elementos também são arrays. Em int m[2][3], cada linha possui três inteiros. Percursos geralmente usam dois laços, respeitando separadamente linhas e colunas.",
        "O segundo tamanho define quantos elementos existem em cada linha.",
        "Inverter limites de linha e coluna pode acessar memória fora da matriz.",
        "Some a diagonal principal da matriz {{10,2},{3,32}} e mostre 42.",
        ["int matriz[2][2]", "for", "matriz[i][i]", "printf"],
        ["42"],
    ),
    "strings": plano(
        "Strings em C são arrays de char terminados por '\\0'. Esse terminador permite que funções descubram onde o texto acaba. O buffer precisa reservar espaço para todos os caracteres e para o terminador.",
        "Uma string válida sempre precisa caber no buffer incluindo o byte '\\0'.",
        "Inicializar char nome[3] com \"Ana\" não deixa espaço para o terminador.",
        "Crie a string \"Linguagem C\" e imprima um caractere por vez usando um laço.",
        ["char texto[]", "texto[i] != '\\0'", "printf"],
        ["Linguagem C"],
    ),
    "strlen": plano(
        "strlen conta caracteres até o primeiro '\\0' e retorna size_t. O terminador não entra na contagem. A função exige uma string válida; um array sem terminador pode provocar leitura fora dos limites.",
        "strlen mede caracteres, não o tamanho total reservado para o array.",
        "Imprimir size_t com %d é incorreto; use %zu.",
        "Use strlen para mostrar o tamanho da palavra \"compilar\".",
        ["#include <string.h>", "strlen", "%zu", "printf"],
        ["8"],
    ),
    "strcpy": plano(
        "strcpy copia uma string, incluindo o terminador, para outro buffer. O destino deve ser grande o bastante e não há verificação automática de limite. Quando o tamanho é incerto, valide antes de copiar.",
        "O destino precisa ter capacidade para strlen(origem) + 1 bytes.",
        "Copiar uma origem maior que o destino causa buffer overflow.",
        "Copie \"C seguro\" para um buffer de 20 caracteres e mostre a cópia.",
        ["#include <string.h>", "char destino[20]", "strcpy", "printf"],
        ["C seguro"],
    ),
    "strcmp": plano(
        "strcmp compara duas strings lexicograficamente. O retorno é zero quando são iguais, negativo quando a primeira vem antes e positivo quando vem depois. Não compare strings com ==, pois isso compara endereços.",
        "Igualdade textual com strcmp é indicada pelo retorno zero.",
        "Usar if (strcmp(a, b)) entra no bloco quando as strings são diferentes.",
        "Compare \"casa\" com \"casa\" e mostre \"Iguais\" quando strcmp retornar zero.",
        ["#include <string.h>", "strcmp", "== 0", "printf"],
        ["Iguais"],
    ),
    "strcat": plano(
        "strcat acrescenta a origem ao final do destino e grava um novo '\\0'. O destino já precisa conter uma string válida e possuir espaço para os dois textos mais o terminador.",
        "Antes de concatenar, a capacidade deve ser maior que strlen(destino) + strlen(origem).",
        "Um destino sem espaço suficiente será escrito além do limite.",
        "Una \"Curso \" e \"de C\" em um buffer de 30 caracteres e mostre o resultado.",
        ["#include <string.h>", "char destino[30]", "strcat", "printf"],
        ["Curso de C"],
    ),
    "fgets": plano(
        "fgets lê no máximo tamanho - 1 caracteres e adiciona '\\0'. Quando encontra Enter, normalmente mantém '\\n' no buffer. É mais segura que funções sem limite e pode ser combinada com strcspn para remover a quebra de linha.",
        "O tamanho passado a fgets deve ser a capacidade real do buffer.",
        "Misturar scanf e fgets sem tratar a quebra de linha pendente pode gerar leitura vazia.",
        "Leia um nome com espaços usando fgets, remova a quebra de linha e mostre \"Ola, NOME\".",
        ["fgets", "sizeof", "strcspn", "printf"],
        ["Ola, Ana Silva"],
        "Ana Silva\n",
    ),
    "memória": plano(
        "Cada objeto ocupa bytes em uma região de memória e possui endereço, tipo e tempo de vida. O tipo orienta quantos bytes ler e como interpretar os bits. sizeof informa o tamanho em bytes sem executar uma leitura do valor.",
        "sizeof retorna size_t e pode variar conforme tipo e plataforma.",
        "Assumir que todos os tipos têm o mesmo tamanho torna o programa não portável.",
        "Mostre quantos bytes int e double ocupam usando sizeof e %zu.",
        ["sizeof(int)", "sizeof(double)", "%zu", "printf"],
        ["int:", "double:"],
    ),
    "operador &": plano(
        "O operador unário & obtém o endereço de um objeto. O resultado deve ser guardado em um ponteiro de tipo compatível. Em printf, endereços são exibidos com %p e convertidos para void *.",
        "&valor produz um ponteiro para valor enquanto esse objeto estiver vivo.",
        "Usar um endereço depois que a variável saiu de escopo cria um ponteiro pendente.",
        "Crie um int 42, obtenha seu endereço e mostre o valor acessado pelo ponteiro.",
        ["int *", "&valor", "*ponteiro", "printf"],
        ["42"],
    ),
    "ponteiros + funções": plano(
        "Passar um ponteiro permite que uma função altere o objeto do chamador. A função deve validar ponteiros que podem ser nulos e desreferenciá-los apenas quando válidos. Essa técnica implementa passagem por referência em C.",
        "Alterar *p modifica o objeto apontado, não apenas uma cópia local.",
        "Desreferenciar NULL causa acesso inválido à memória.",
        "Crie trocar(int *a, int *b), troque 10 e 42 e mostre \"42 10\".",
        ["void trocar(int *a, int *b)", "*a", "*b", "trocar(&", "printf"],
        ["42 10"],
    ),
    "ponteiros + arrays": plano(
        "Em muitas expressões, o nome de um array vira ponteiro para seu primeiro elemento. valor[i] equivale a *(valor + i). A aritmética avança em unidades do tipo apontado, não em bytes crus.",
        "p + 1 aponta para o próximo elemento do tipo de p.",
        "Avançar além do final e desreferenciar o ponteiro é inválido.",
        "Percorra {10, 20, 12} somente com um ponteiro e mostre a soma 42.",
        ["int valores[3]", "int *", "*(p + i)", "for", "printf"],
        ["42"],
    ),
    "ponteiro para ponteiro": plano(
        "Um ponteiro para ponteiro guarda o endereço de outro ponteiro. Ele aparece quando uma função precisa alterar o próprio ponteiro do chamador e em estruturas como vetores de strings. Cada * remove um nível de indireção.",
        "**pp acessa o objeto final apontado por p, cujo endereço está em pp.",
        "Confundir os níveis de indireção leva a tipos incompatíveis e acessos inválidos.",
        "Crie valor, p e pp; altere valor para 42 por meio de **pp e imprima-o.",
        ["int **", "&p", "**pp = 42", "printf"],
        ["42"],
    ),
    "malloc": plano(
        "malloc reserva uma quantidade de bytes na heap e devolve void *. Em C, a conversão para outro ponteiro é implícita. Sempre verifique NULL, inicialize os elementos antes da leitura e libere a memória quando terminar.",
        "malloc não inicializa o conteúdo da área reservada.",
        "Usar o ponteiro sem testar NULL pode falhar quando a alocação não é atendida.",
        "Aloque três int, guarde 10, 20 e 12, some-os, mostre 42 e libere a memória.",
        ["malloc(3 * sizeof", "if", "NULL", "free", "printf"],
        ["42"],
    ),
    "calloc": plano(
        "calloc recebe quantidade e tamanho de cada elemento, verifica a multiplicação internamente e zera todos os bytes reservados. Ainda é obrigatório verificar NULL e chamar free.",
        "calloc inicia os bytes da área alocada com zero.",
        "Memória zerada não substitui a inicialização lógica de tipos complexos.",
        "Use calloc para criar quatro int zerados, some 42 ao último e mostre todos.",
        ["calloc(4, sizeof", "NULL", "free", "printf"],
        ["0 0 0 42"],
    ),
    "realloc": plano(
        "realloc redimensiona um bloco e pode movê-lo para outro endereço. Se falhar, o bloco original continua válido; por isso guarde o retorno em um ponteiro temporário. Novos bytes não são inicializados.",
        "Só substitua o ponteiro original depois de confirmar que realloc teve sucesso.",
        "Atribuir realloc diretamente ao único ponteiro pode perder o bloco em caso de falha.",
        "Aloque dois int, aumente para três com ponteiro temporário e mostre a soma 42.",
        ["malloc", "realloc", "temporario", "NULL", "free", "printf"],
        ["42"],
    ),
    "free": plano(
        "free devolve à heap um bloco obtido por malloc, calloc ou realloc. Depois da liberação, o ponteiro não pode ser desreferenciado. Atribuir NULL reduz o risco de uso acidental e free(NULL) é permitido.",
        "Cada alocação ainda pertencente ao programa deve ser liberada uma única vez.",
        "Double free e uso após free são comportamentos indefinidos.",
        "Aloque um int com valor 42, mostre-o, libere e atribua NULL ao ponteiro.",
        ["malloc", "free", "= NULL", "printf"],
        ["42"],
    ),
    "memory leak": plano(
        "Vazamento acontece quando um bloco alocado deixa de ser alcançável sem ser liberado. Em processos longos, pequenos vazamentos se acumulam. Defina claramente qual parte do programa é dona de cada alocação.",
        "Perder o último ponteiro para um bloco impede sua liberação posterior.",
        "Sobrescrever um ponteiro dono com nova alocação sem free vaza o bloco antigo.",
        "Crie uma função que aloque um int, use o valor 42 e garanta free antes de retornar.",
        ["malloc", "NULL", "free", "return", "printf"],
        ["42"],
    ),
    "structs": plano(
        "struct agrupa campos relacionados, possivelmente de tipos diferentes, em um único objeto. O acesso usa ponto; por um ponteiro, usa ->. A estrutura ajuda a modelar entidades do domínio.",
        "Cada instância de struct possui seu próprio conjunto de campos.",
        "Copiar uma struct copia seus campos, mas ponteiros internos continuam apontando para os mesmos locais.",
        "Crie struct Produto com nome e preco; inicialize \"Livro\", 42.0 e mostre os campos.",
        ["struct Produto", "char nome", "double preco", ".nome", ".preco", "printf"],
        ["Livro", "42.00"],
    ),
    "typedef": plano(
        "typedef cria um apelido para um tipo existente. Ele não cria um tipo com comportamento novo, mas simplifica assinaturas e declarações, especialmente com structs e ponteiros.",
        "typedef melhora a legibilidade sem reservar memória ou criar objetos.",
        "Esconder ponteiros em typedef pode tornar menos claro quem precisa liberar memória.",
        "Crie typedef struct para Ponto, inicialize x=19 e y=23 e mostre a soma 42.",
        ["typedef struct", "} Ponto;", "Ponto ponto", "printf"],
        ["42"],
    ),
    "unions": plano(
        "Em uma union, todos os membros compartilham a mesma região de memória. Apenas o membro escrito mais recentemente deve ser considerado ativo. Unions são úteis para representar alternativas, normalmente acompanhadas de uma enum que informa o tipo ativo.",
        "O tamanho de uma union comporta seu maior membro, com possível alinhamento.",
        "Ler um membro diferente do ativo é dependente da implementação ou inválido para a lógica.",
        "Crie union Numero com int e double, grave o int 42 e mostre o membro ativo.",
        ["union Numero", "int inteiro", "double decimal", ".inteiro = 42", "printf"],
        ["42"],
    ),
    "enum": plano(
        "enum define constantes inteiras nomeadas e torna estados mais legíveis. Por padrão, o primeiro valor é zero e os seguintes aumentam em um, mas valores explícitos podem ser usados.",
        "Nomes de enum substituem números mágicos em estados e opções.",
        "Uma variável enum ainda pode receber inteiros inválidos se o programa não validar.",
        "Crie enum Status com PENDENTE, ATIVO e CONCLUIDO; use ATIVO e mostre \"Ativo\".",
        ["enum Status", "PENDENTE", "ATIVO", "CONCLUIDO", "switch", "printf"],
        ["Ativo"],
    ),
    "fopen": plano(
        "fopen abre um arquivo e retorna FILE *. Modos como \"r\", \"w\" e \"a\" controlam leitura, recriação e acréscimo. O retorno NULL precisa ser tratado porque caminho, permissão ou armazenamento podem falhar.",
        "O modo \"w\" cria o arquivo ou apaga seu conteúdo anterior.",
        "Usar FILE * sem verificar NULL pode causar falha nas operações seguintes.",
        "Abra \"dados.txt\" para escrita, valide o ponteiro, mostre \"Arquivo aberto\" e feche-o.",
        ["FILE *", "fopen", "\"w\"", "NULL", "fclose", "printf"],
        ["Arquivo aberto"],
    ),
    "fclose": plano(
        "fclose finaliza o fluxo, descarrega buffers pendentes e libera recursos associados. Seu retorno deve ser verificado quando a integridade da gravação é importante. O FILE * não deve ser reutilizado depois.",
        "Fechar o fluxo é necessário mesmo quando o programa termina logo depois.",
        "Esquecer fclose pode perder dados em buffer e consumir descritores.",
        "Crie um arquivo, grave 42, feche verificando o retorno e mostre \"Arquivo fechado\".",
        ["fopen", "fprintf", "fclose", "== 0", "printf"],
        ["Arquivo fechado"],
    ),
    "fprintf": plano(
        "fprintf funciona como printf, mas recebe um FILE * de destino. Ele grava texto formatado e retorna a quantidade de caracteres, ou valor negativo em erro.",
        "A mesma regra de compatibilidade de formatos de printf vale para fprintf.",
        "Não verificar a abertura antes de fprintf pode desreferenciar um fluxo nulo.",
        "Grave \"Resposta: 42\" em resultado.txt, feche e mostre \"Gravado\".",
        ["fopen", "fprintf", "Resposta: %d", "fclose", "printf"],
        ["Gravado"],
    ),
    "fscanf": plano(
        "fscanf lê dados formatados de um fluxo. Como scanf, retorna quantos itens foram convertidos. O laço de leitura deve testar esse retorno, nunca feof antes da tentativa.",
        "A condição correta de leitura compara o retorno com a quantidade esperada.",
        "while (!feof(arquivo)) costuma processar uma leitura inválida no final.",
        "Grave 19 e 23 em um arquivo, reabra, leia com fscanf e mostre a soma 42.",
        ["fopen", "fprintf", "fscanf", "== 2", "fclose", "printf"],
        ["42"],
    ),
    ".h": plano(
        "Arquivos .h descrevem a interface compartilhada: protótipos, tipos e constantes. Eles são incluídos pelo pré-processador. Implementações comuns ficam em .c para evitar múltiplas definições.",
        "Um cabeçalho informa ao compilador como usar funções definidas em outra unidade.",
        "Definir variáveis globais comuns diretamente no .h pode duplicá-las durante o linking.",
        "Simule uma interface no mesmo arquivo: declare o protótipo somar antes de main e defina a função depois.",
        ["int somar(int a, int b);", "int main", "somar(19, 23)", "return a + b"],
        ["42"],
    ),
    ".c": plano(
        "Cada arquivo .c é uma unidade de tradução compilada separadamente. Ele inclui os cabeçalhos necessários e contém implementações. Depois, os arquivos objeto são ligados em um executável.",
        "Separar implementações reduz recompilações e melhora a organização.",
        "Incluir diretamente outro arquivo .c pode causar símbolos duplicados.",
        "Organize no arquivo único uma seção de protótipos, main e implementação da função triplo.",
        ["int triplo(int", "int main", "triplo(14)", "return n * 3"],
        ["42"],
    ),
    "include guards": plano(
        "Include guards usam #ifndef, #define e #endif para que um cabeçalho seja processado uma única vez por unidade de tradução. O nome da macro deve ser único no projeto.",
        "A proteção evita redefinições quando o mesmo cabeçalho chega por caminhos diferentes.",
        "Reutilizar a mesma macro de guarda em dois cabeçalhos pode ocultar um deles.",
        "Demonstre as diretivas de uma guarda chamada MATEMATICA_H e use uma função dobro no mesmo arquivo.",
        ["#ifndef MATEMATICA_H", "#define MATEMATICA_H", "#endif", "dobro(21)", "printf"],
        ["42"],
    ),
    "stdio": plano(
        "stdio.h declara recursos de entrada e saída, como printf, scanf, FILE, fopen e fgets. Os fluxos stdin, stdout e stderr representam entrada, saída normal e saída de erros.",
        "stderr é apropriado para mensagens de erro e pode ser separado da saída normal.",
        "Usar funções sem incluir o cabeçalho correto impede a verificação adequada da assinatura.",
        "Leia um inteiro com scanf e mostre seu dobro usando recursos de stdio.",
        ["#include <stdio.h>", "scanf", "printf", "* 2"],
        ["42"],
        "21\n",
    ),
    "stdlib": plano(
        "stdlib.h reúne alocação dinâmica, conversões, ordenação, busca e controle do processo. Exemplos incluem malloc, free, strtol, qsort, EXIT_SUCCESS e EXIT_FAILURE.",
        "strtol permite validar conversões numéricas melhor que atoi.",
        "atoi não informa de forma confiável se o texto era inválido.",
        "Converta a string \"42\" com strtol, valide o final da leitura e mostre o número.",
        ["#include <stdlib.h>", "strtol", "char *fim", "*fim == '\\0'", "printf"],
        ["42"],
    ),
    "string": plano(
        "string.h declara operações sobre bytes e strings, como strlen, strcmp, memcpy e memset. A maioria pressupõe buffers válidos e capacidade suficiente; a biblioteca não conhece o tamanho real do array.",
        "Funções de string dependem do terminador '\\0'.",
        "Confundir quantidade de caracteres com capacidade do buffer causa overflow.",
        "Copie \"C\", concatene \"11\" e confirme com strcmp que o resultado é \"C11\".",
        ["#include <string.h>", "strcpy", "strcat", "strcmp", "printf"],
        ["C11", "correto"],
    ),
    "math": plano(
        "math.h declara funções matemáticas e macros de ponto flutuante. Algumas plataformas exigem ligar a biblioteca libm. Trabalhe com double, valide domínios e considere tolerância em comparações.",
        "Funções matemáticas operam com aproximações de ponto flutuante.",
        "Calcular raiz de número negativo sem tratar o domínio produz valor inválido.",
        "Use sqrt para calcular a raiz de 1764 e mostre sem casas decimais.",
        ["#include <math.h>", "sqrt", "%.0f", "printf"],
        ["42"],
    ),
    "bitwise": plano(
        "Operadores &, |, ^, ~, << e >> trabalham com bits individuais de inteiros. Eles são diferentes dos operadores lógicos. Use tipos unsigned para deslocamentos mais previsíveis.",
        "AND preserva apenas bits ligados nos dois operandos; OR liga bits presentes em qualquer um.",
        "Deslocar por quantidade negativa ou maior que a largura do tipo é inválido.",
        "Use deslocamento à esquerda para transformar 21 em 42 e mostre o resultado.",
        ["unsigned", "<< 1", "printf"],
        ["42"],
    ),
    "máscaras": plano(
        "Uma máscara seleciona bits que representam opções independentes. OR ativa, AND testa e AND com complemento desativa uma opção. Constantes com 1u << posição documentam cada flag.",
        "O teste (valor & MASCARA) != 0 verifica se uma flag está ativa.",
        "Usar números binários sem nomes torna as permissões difíceis de revisar.",
        "Defina flags LER, ESCREVER e EXECUTAR; ative LER e EXECUTAR e mostre \"Pode executar\".",
        ["1u <<", "|", "& EXECUTAR", "printf"],
        ["Pode executar"],
    ),
    "erros de sintaxe": plano(
        "Erros de sintaxe violam a gramática da linguagem: delimitadores ausentes, tokens inválidos ou declarações incompletas. O compilador informa arquivo, linha e contexto. Corrija primeiro a mensagem inicial e compile novamente.",
        "A linha indicada pode ser apenas onde o compilador percebeu um erro iniciado antes.",
        "Tentar corrigir todas as mensagens de uma vez pode atacar efeitos em vez da causa.",
        "Escreva uma versão correta que declare int resposta = 42 e a imprima sem warnings.",
        ["int resposta = 42;", "printf", "return 0;"],
        ["42"],
    ),
    "erros lógicos": plano(
        "Erros lógicos compilam, mas produzem resposta incorreta. Casos de teste pequenos, valores de fronteira e comparação com um resultado calculado à mão ajudam a localizá-los.",
        "Um teste deve possuir entrada e resultado esperado definidos antes da execução.",
        "Testar apenas o caminho mais comum deixa condições de borda sem cobertura.",
        "Corrija a fórmula da média de 8, 10 e 12 e mostre 10.00.",
        ["8.0", "10.0", "12.0", "/ 3.0", "%.2f"],
        ["10.00"],
    ),
    "debug": plano(
        "Depurar é observar o estado do programa, formular uma hipótese e testá-la. Prints temporários, debugger, asserts e execução passo a passo revelam onde o estado diverge do esperado.",
        "Uma boa depuração reduz o problema até a menor entrada que ainda reproduz a falha.",
        "Alterar várias partes ao mesmo tempo impede saber qual mudança resolveu o defeito.",
        "Percorra {10, 20, 12}, mostre cada valor com seu índice e ao final \"Total: 42\".",
        ["int valores[3]", "for", "Indice", "Total", "printf"],
        ["Indice 0", "Indice 1", "Indice 2", "Total: 42"],
    ),
    "gcc": plano(
        "GCC pode pré-processar, compilar, montar e ligar. Opções como -std=c11, -Wall, -Wextra e -pedantic ajudam a encontrar problemas cedo. -o escolhe o nome do executável.",
        "Warnings adicionais melhoram a qualidade, mas não substituem testes.",
        "Compilar sem declarar um padrão pode aceitar extensões e variar entre ambientes.",
        "Crie um programa compatível com C11, sem variável não usada, que mostre \"GCC OK\".",
        ["int main(void)", "printf", "return 0"],
        ["GCC OK"],
    ),
    "linking": plano(
        "O linker combina arquivos objeto e bibliotecas, resolvendo símbolos usados e definidos. Erro de referência indefinida indica que a declaração foi vista, mas nenhuma implementação compatível foi ligada.",
        "Compilação valida cada unidade; linking resolve as conexões entre elas.",
        "Definir a mesma função global em dois arquivos causa múltipla definição.",
        "Simule duas unidades em um arquivo: declare resposta, chame em main e defina-a depois retornando 42.",
        ["int resposta(void);", "resposta()", "int resposta(void)", "return 42"],
        ["42"],
    ),
    "makefile": plano(
        "Make usa alvos, dependências e comandos para reconstruir apenas o necessário. Variáveis como CC e CFLAGS centralizam o compilador e as opções. Linhas de comando tradicionais começam com tabulação.",
        "Uma regra descreve como produzir um alvo a partir de suas dependências.",
        "Dependências incompletas deixam binários desatualizados depois de mudanças.",
        "No editor C, represente a ideia de build com constantes CC e CFLAGS e mostre \"gcc -std=c11 -Wall main.c\".",
        ["CC", "CFLAGS", "gcc", "-std=c11", "-Wall", "printf"],
        ["gcc -std=c11 -Wall main.c"],
    ),
    "buffer overflow": plano(
        "Buffer overflow acontece quando uma escrita ultrapassa a capacidade reservada. Em C, isso pode corromper dados, desviar o fluxo e abrir falhas de segurança. Limite leituras e calcule capacidades incluindo '\\0'.",
        "A entrada máxima de uma string deve ser menor que a capacidade do buffer.",
        "gets e scanf(\"%s\") sem largura não impedem escrita além do array.",
        "Leia uma palavra em char nome[10] usando largura máxima 9 e mostre o valor.",
        ["char nome[10]", "scanf(\"%9s\"", "printf"],
        ["Seguro"],
        "Seguro\n",
    ),
    "validação": plano(
        "Validação confirma formato, faixa e regras antes de usar um dado. Separe entrada inválida de valor válido fora do intervalo e forneça uma resposta previsível para cada caso.",
        "O retorno da função de leitura deve ser verificado antes de acessar a variável.",
        "Validar somente depois do cálculo permite que um dado inválido já tenha causado dano.",
        "Leia uma idade inteira; aceite apenas de 0 a 120 e mostre \"Idade valida\" ou \"Entrada invalida\".",
        ["scanf", "== 1", ">= 0", "<= 120", "printf"],
        ["Idade valida"],
        "42\n",
    ),
    "listas": plano(
        "Uma lista encadeada armazena nós ligados por ponteiros. Inserções no início são O(1), mas o acesso por posição exige percurso. Cada nó alocado precisa ser liberado.",
        "O último nó aponta para NULL e encerra o percurso.",
        "Perder o ponteiro para o próximo nó antes de free impede continuar a liberação.",
        "Crie uma lista de três nós com 10, 20 e 12; percorra, some 42 e libere todos.",
        ["struct No", "struct No *proximo", "malloc", "while", "free"],
        ["42"],
    ),
    "pilhas": plano(
        "Pilha segue LIFO: o último elemento inserido é o primeiro removido. Push adiciona no topo e pop remove do topo. Pode ser implementada com array e índice ou lista encadeada.",
        "Toda operação pop deve verificar se a pilha está vazia.",
        "Incrementar o topo além da capacidade escreve fora do array.",
        "Implemente push e pop em uma pilha de int; empilhe 10 e 42 e mostre o primeiro pop.",
        ["push", "pop", "topo", "pilha", "printf"],
        ["42"],
    ),
    "filas": plano(
        "Fila segue FIFO: o primeiro a entrar é o primeiro a sair. Em arrays, uma fila circular reaproveita posições por meio de índices de início e fim.",
        "Remoção acontece no início e inserção no final.",
        "Mover todos os elementos a cada remoção torna a implementação desnecessariamente lenta.",
        "Implemente uma fila simples, enfileire 42 e 10 e mostre o primeiro removido.",
        ["enfileirar", "desenfileirar", "inicio", "fim", "printf"],
        ["42"],
    ),
    "árvores": plano(
        "Uma árvore binária organiza nós com filhos esquerdo e direito. Em uma árvore de busca, menores ficam à esquerda e maiores à direita. Percursos recursivos visitam todos os nós em ordens diferentes.",
        "O percurso em ordem de uma árvore de busca produz valores ordenados.",
        "Uma árvore muito desbalanceada pode degradar operações para tempo linear.",
        "Monte nós 20, 10 e 42 e faça percurso em ordem mostrando \"10 20 42\".",
        ["struct No", "*esquerda", "*direita", "emOrdem", "printf"],
        ["10 20 42"],
    ),
    "busca linear": plano(
        "A busca linear examina elementos do início ao fim até encontrar o alvo. Funciona em dados não ordenados e tem custo O(n) no pior caso. Pode parar assim que a posição é descoberta.",
        "O algoritmo não exige que o vetor esteja ordenado.",
        "Continuar após encontrar o alvo desperdiça trabalho quando só uma posição é necessária.",
        "Busque 42 em {5, 12, 42, 9} e mostre \"Posicao: 2\".",
        ["for", "valores[i] == alvo", "break", "printf"],
        ["Posicao: 2"],
    ),
    "bubble sort": plano(
        "Bubble sort compara vizinhos e troca os que estão fora de ordem. Após cada passada, um dos maiores elementos chega ao final. É simples para estudo, mas custa O(n²).",
        "Uma passada sem trocas permite encerrar cedo porque o vetor já está ordenado.",
        "Usar o limite interno completo em todas as passadas faz comparações desnecessárias.",
        "Ordene {42, 7, 19, 3} em ordem crescente e mostre os quatro valores.",
        ["for", "v[j] > v[j + 1]", "troca", "printf"],
        ["3 7 19 42"],
    ),
    "eficiência": plano(
        "Eficiência considera como tempo e memória crescem com a entrada. O(n) cresce linearmente; O(n²) cresce quadraticamente. Meça apenas depois de escolher um algoritmo correto e dados representativos.",
        "Complexidade descreve crescimento, não o tempo exato em segundos.",
        "Otimizar microdetalhes não compensa escolher um algoritmo inadequado.",
        "Conte em um único laço quantos valores pares existem em {2,5,8,11,42} e mostre 3.",
        ["for", "% 2 == 0", "contador++", "printf"],
        ["3"],
    ),
    "calculadora": plano(
        "Uma calculadora reúne entrada, decisão, operadores e validação. Separe o cálculo em função e trate divisão por zero. Um menu claro define operações aceitas.",
        "Cada operador deve ter um caminho explícito e um resultado previsível.",
        "Executar divisão antes de validar o divisor pode encerrar o programa.",
        "Leia dois double e um operador; para a entrada 20 + 22, mostre \"Resultado: 42.00\".",
        ["scanf", "switch", "case '+'", "double", "printf"],
        ["Resultado: 42.00"],
        "20 + 22\n",
    ),
    "cadastro": plano(
        "Um cadastro combina struct, validação e armazenamento. Campos de texto precisam de limites e cada registro deve possuir uma identidade ou posição bem definida.",
        "Modelar o registro em uma struct mantém os campos relacionados.",
        "Ler texto sem limite pode corromper o registro seguinte.",
        "Crie struct Pessoa, leia nome sem espaços e idade, e mostre \"NOME tem IDADE anos\".",
        ["struct Pessoa", "char nome[30]", "scanf(\"%29s\"", "idade", "printf"],
        ["Ana tem 42 anos"],
        "Ana 42\n",
    ),
    "agenda": plano(
        "Uma agenda acrescenta busca e organização a um cadastro. Cada contato pode conter nome e telefone; funções separadas cuidam de inserir, listar e localizar.",
        "A busca textual deve usar strcmp, não ==.",
        "Não controlar a quantidade de contatos pode ultrapassar a capacidade do vetor.",
        "Crie dois contatos fixos, busque \"Ana\" com strcmp e mostre seu telefone 4242-4242.",
        ["struct Contato", "strcmp", "for", "telefone", "printf"],
        ["4242-4242"],
    ),
    "jogo terminal": plano(
        "Jogos de terminal usam um laço principal: ler ação, atualizar estado e mostrar resultado. Números aleatórios devem ser semeados uma vez, mas testes ficam melhores com alvos determinísticos.",
        "O estado do jogo deve ter uma condição clara de vitória ou encerramento.",
        "Sem limite de tentativas ou opção de saída, o laço pode prender o usuário.",
        "Crie um jogo de adivinhação com alvo 42; leia tentativas até acertar e mostre \"Acertou\".",
        ["while", "scanf", "alvo = 42", "if", "printf"],
        ["Acertou"],
        "10\n42\n",
    ),
    "sistema biblioteca": plano(
        "Um sistema de biblioteca modela livros, disponibilidade e operações de empréstimo. Regras do domínio devem ficar em funções para impedir estados impossíveis.",
        "Um empréstimo só pode ocorrer quando o livro está disponível.",
        "Alterar o campo diretamente em vários lugares duplica regras e facilita inconsistências.",
        "Crie struct Livro com disponível; implemente emprestar e mostre \"Emprestado\" uma única vez.",
        ["struct Livro", "disponivel", "emprestar", "if", "printf"],
        ["Emprestado"],
    ),
    "editor texto": plano(
        "Um editor simples trabalha com buffer, posição atual e comandos de alteração. Toda inserção precisa respeitar a capacidade e preservar o terminador da string.",
        "Antes de anexar texto, calcule o espaço livre no buffer.",
        "Concatenar sem verificar capacidade é uma fonte direta de overflow.",
        "Em um buffer de 50, una \"Aprender \" e \"C\" com verificação de espaço e mostre o texto.",
        ["char texto[50]", "strlen", "sizeof", "strcat", "printf"],
        ["Aprender C"],
    ),
    "projeto final": plano(
        "O projeto final integra modelagem, funções, validação, persistência e testes. Comece por requisitos pequenos, defina estruturas de dados e implemente um fluxo completo antes de acrescentar recursos.",
        "Uma entrega incremental funcionando é mais verificável que muitos recursos incompletos.",
        "Misturar interface, regras e armazenamento em uma única função torna mudanças arriscadas.",
        "Implemente um resumo de notas: leia três valores, valide, calcule média em função e mostre \"Media: 8.00\".",
        ["double calcularMedia", "scanf", "== 3", "/ 3.0", "printf"],
        ["Media: 8.00"],
        "7 8 9\n",
    ),
}


def obter_plano(conteudo):
    return PLANOS_LICOES.get(conteudo)
